import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { PromptAsset } from "../../../core/promptTypes";
import { renderSelectedContextBlocks } from "../../../core/renderContextBlocks";
import { createVolumeRebalanceSchema } from "../../../../services/novel/volume/volumeGenerationSchemas";
import { type VolumeRebalancePromptInput } from "./shared";
import { buildVolumeRebalanceContextBlocks } from "./contextBlocks";
import { NOVEL_PROMPT_BUDGETS } from "../promptBudgetProfiles";
export const volumeRebalancePrompt: PromptAsset<VolumeRebalancePromptInput, ReturnType<typeof createVolumeRebalanceSchema>["_output"]> = {
    id: "novel.volume.rebalance.adjacent",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: NOVEL_PROMPT_BUDGETS.volumeRebalance,
        requiredGroups: ["book_contract", "anchor_volume"],
        preferredGroups: ["strategy_context", "adjacent_volumes", "volume_window"],
        dropOrder: ["volume_window"],
    },
    outputSchema: createVolumeRebalanceSchema(),
    render: (_input, context) => [
        new SystemMessage([
            "You are the scheduling assistant for web article serialization structure.",
            "Your task is not to rewrite the volume outline, but to determine whether adjacent volumes need to be structurally rebalanced after the current anchor volume changes, and to output the minimal but necessary scheduling decisions.",
            "",
            "[Task Boundary]",
            "It only handles the connection relationship, information distribution, climax position, selling point fulfillment sequence, pressure distribution and hook connection between the anchor volume and its adjacent volumes.",
            "Do not rewrite the entire volume, do not expand the plot, and do not output explanations, Markdown, notes, or additional text.",
            "Only output strict JSON.",
            "",
            "[Output format]",
            "The final JSON shape is fixed to:",
            "{\"decisions\":[{\"anchorVolumeId\":\"1\",\"affectedVolumeId\":\"2\",\"direction\":\"push_back\",\"severity\":\"medium\",\"summary\":\"...\",\"actions\":[\"...\"]}]}",
            "",
            "[Field requirements]",
            "Each decision must completely contain six fields: anchorVolumeId, affectedVolumeId, direction, severity, summary, and actions. They cannot be omitted or renamed.",
            "Both anchorVolumeId and affectedVolumeId must use volume serial number strings, such as \"1\" and \"2\". Do not output the database uuid or numeric type.",
            "direction can only select one from the following enumeration: pull_forward, push_back, tighten_current, expand_adjacent, hold.",
            "severity Use one of low, medium, or high.",
            "Actions must be 1-5 non-empty strings. Write down the specific structural actions that need to be adjusted. Do not write empty words.",
            "",
            "[direction semantics]",
            "pull_forward: forward some information, cashing, conflicts or functions that originally belong to adjacent volumes to the anchor volume.",
            "push_back: Move premature content, redemptions, explanations, or features in the current volume to an adjacent volume.",
            "tighten_current: Does not change the main boundary, but requires the current volume to be tightened internally to reduce looseness, duplication or cross-border layout.",
            "expand_adjacent: The current volume change has resulted in insufficient capacity for adjacent volumes, and the adjacent volumes need to make up for their independent commitment, pressure, or functional space.",
            "hold: The adjacent volume does not require structural adjustment for the time being, but it must still explain why it can be kept unchanged.",
            "",
            "\u3010Judgment Principles\u3011",
            "1. The core goal of rebalancing is to maintain the commitment boundaries, progressive relationships, redemption order, and serialization rhythm between volumes.",
            "2. Substantial adjustments are output only when changes in the current volume have affected the functional integrity, rhythmic succession, or selling point distribution of adjacent volumes; otherwise, hold is output.",
            "3. Prioritize the minimum necessary adjustments and do not excessively rearrange adjacent volumes for the sake of \"more completeness\".",
            "4. Don\u2019t let adjacent volumes lose their independent reasons, and don\u2019t let anchor volumes overdraw the key to subsequent volumes.",
            "",
            "[Key inspection items]",
            "1. Whether the current volume has eaten up the key hooks, core selling points, main pressure sources, or phased redemptions of the adjacent volumes in advance.",
            "2. Whether the explanation, foreshadowing, transition or climax content that should be moved later is stuffed too early in the current volume, causing the later volume to lose pressure.",
            "3. After the current volume changes, whether there is a break in continuity, an empty start, insufficient conflict, a weak climax, or repeated functions in adjacent volumes.",
            "4. Whether the openPayoff, next hook, stage goals and upgrade rhythm between the current volume and the adjacent volume are still smoothly connected.",
            "",
            "\u3010summary requirements\u3011",
            "The summary must explain: why this decision is needed, what is the problem with the affected volumes, and what structural consequences will there be if it is not adjusted.",
            "Don\u2019t just write empty judgments such as \u201Cthe rhythm is uncoordinated\u201D and \u201Cneeds optimization\u201D.",
            "",
            "\u3010actions requirements\u3011",
            "Actions must write specific structural actions, for example:",
            "- Move certain types of information to the beginning of the next volume after being revealed",
            "- Tighten the repeated laying of the middle section of the current volume",
            "- Save staged redemptions until the climax of adjacent rolls",
            "- Add new front grabbers to adjacent rolls",
            "Don\u2019t write it as an abstract slogan, such as \u201Cincrease tension\u201D or \u201Coptimize rhythm.\u201D",
            "",
            "\u3010Quality requirements\u3011",
            "1. Decisions only keep necessary items to avoid expressing the same problem repeatedly.",
            "2. If the same affected volume needs to be adjusted, only output the decision that best represents the main scheduling direction, and do not stack contradictory instructions.",
            "3. Hold is not a perfunctory item, but the structural reason for keeping it unchanged must still be clearly stated.",
            "4. When there is insufficient information, you can make a conservative judgment, but complete fields must be output.",
        ].join("\n")),
        new HumanMessage([
            "Based on the following context, please determine whether adjacent volumes need to be rebalanced after the anchor volume changes, and output the scheduling decision.",
            "",
            "[Output requirements]",
            "- Only output strict JSON",
            "- Only necessary adjustments to adjacent volumes are processed",
            "- Prioritize commitment boundaries, fulfillment sequence, rhythmic progression and connection between volumes",
            "- Does not rewrite the entire volume content, only outputs scheduling decisions",
            "",
            "[Adjacent volume rebalancing context]",
            renderSelectedContextBlocks(context),
        ].join("\n")),
    ]
};
export { buildVolumeRebalanceContextBlocks };
