import type { StoryModeProfile } from "@ai-novel/shared/types/storyMode";
export interface StoryModeSeedNode {
    id: string;
    name: string;
    description: string;
    template: string;
    profile: StoryModeProfile;
    children: Array<{
        id: string;
        name: string;
        description: string;
        template: string;
        profile: StoryModeProfile;
    }>;
}
function buildProfile(input: Partial<StoryModeProfile> & Pick<StoryModeProfile, "coreDrive" | "readerReward">): StoryModeProfile {
    return {
        coreDrive: input.coreDrive,
        readerReward: input.readerReward,
        progressionUnits: input.progressionUnits ?? ["relationship advancement", "Fulfillment of stage goals"],
        allowedConflictForms: input.allowedConflictForms ?? ["Low to medium intensity conflict consistent with primary drive"],
        forbiddenConflictForms: input.forbiddenConflictForms ?? ["Unrelated high-pressure bloody conflict"],
        conflictCeiling: input.conflictCeiling ?? "medium",
        resolutionStyle: input.resolutionStyle ?? "Prioritize solving problems in a way that conforms to this model, rather than forcibly escalating conflicts.",
        chapterUnit: input.chapterUnit ?? "Each chapter is organized around a clear advancing unit.",
        volumeReward: input.volumeReward ?? "At the end of the volume, a staged realization is provided to allow readers to confirm that this line is worth continuing to pursue.",
        mandatorySignals: input.mandatorySignals ?? ["Main drive keeps showing up", "Readers expect repeated confirmation"],
        antiSignals: input.antiSignals ?? ["Long-term deviation from main drive", "The intensity of the conflict is out of control"],
    };
}
export const BUILT_IN_STORY_MODE_SEEDS: StoryModeSeedNode[] = [
    {
        id: "story_mode_power_root",
        name: "Power and Reversal",
        description: "A reading model driven by the realization of advantages, establishment of prestige, contrast and staged suppression.",
        template: "Emphasis on advantage display, situation reversal and clear readers' point realization.",
        profile: buildProfile({
            coreDrive: "Continuously create a sense of excitement through the realization of the protagonist's advantages, cognitive contrast and situation reversal.",
            readerReward: "The reader continues to see the satisfaction of suppression, power building, reversal, and rules being rewritten.",
            progressionUnits: ["establish prestige", "break doubts", "Expand influence", "Staged crushing"],
            allowedConflictForms: ["Identity suppression", "cognitive bias", "power challenge", "Rule rewriting"],
            forbiddenConflictForms: ["Survival from long-term disadvantage", "Continuing to be defeated and not fighting back"],
            conflictCeiling: "high",
            resolutionStyle: "Realize the protagonist's advantages as soon as possible and let the conflict become a stage to demonstrate power and status.",
            chapterUnit: "Each chapter advances the result of suppressing, reversing or establishing power.",
            volumeReward: "The end of the volume forms a larger picture of recognition, fear, surrender, or rewriting of order.",
            mandatorySignals: ["sense of superiority", "sense of contrast", "A scene of establishing authority"],
            antiSignals: ["The protagonist is passive for a long time", "It's been a while since I've been happy."],
        }),
        children: [
            {
                id: "story_mode_invincible",
                name: "Overwhelming Advantage",
                description: "The protagonist's advantages are very clear, and the suspense comes from the presentation method and order rewriting, not from the existential crisis.",
                template: "Establish the upper limit of the protagonist as soon as possible, and focus on suppressing, breaking the situation, establishing power and changing the rules.",
                profile: buildProfile({
                    coreDrive: "Let the protagonist crush the resistance with obvious advantages and constantly refresh other people's perceptions.",
                    readerReward: "The reader sees a clear repression and establishment of status every few chapters.",
                    progressionUnits: ["Show your cards", "Suppress your opponent", "extended deterrence", "Rewrite rules"],
                    allowedConflictForms: ["Misidentification", "Power provocation", "Expert test"],
                    forbiddenConflictForms: ["Long-term hiding and development", "A sadistic story about being unable to fight back for a long time"],
                    conflictCeiling: "high",
                    resolutionStyle: "The conflict ended with quick counterattacks and high-position crushing.",
                    chapterUnit: "A single chapter revolves around a suppression, temptation or establishment of power.",
                    volumeReward: "At the end of the volume, a new power structure or wider recognition is formed.",
                    mandatorySignals: ["Strong aura", "Shocked onlookers", "leapfrog suppression"],
                    antiSignals: ["The protagonist is weak for a long time like a normal upgrade story", "Core advantages are deliberately blocked"],
                }),
            },
            {
                id: "story_mode_face_slap",
                name: "Public Reversal",
                description: "Misjudgment, contempt and reversal of humiliation constitute high-frequency pleasure points.",
                template: "Make a misjudgment first, and then reverse it accurately. The slap in the face must be recovered in time.",
                profile: buildProfile({
                    coreDrive: "Continuously realize the pleasure of high-frequency slaps in the face through other people's misjudgments and subsequent reversals.",
                    readerReward: "Readers constantly see the despised being recycled and regurgitated on the spot.",
                    progressionUnits: ["Misjudgment foreshadowing", "identity reversal", "Public recycling", "Fermentation of public opinion"],
                    allowedConflictForms: ["despise", "public humiliation", "Competition for resources"],
                    forbiddenConflictForms: ["The bedding is too long but not recycled", "There is no actual impact after being slapped in the face"],
                    resolutionStyle: "Complete reversals and recoveries when you need to prove yourself most.",
                    chapterUnit: "This single chapter focuses on creating a closed loop of misjudgment and recovery.",
                    volumeReward: "At the end of the volume, the protagonist changes from being despised to a central figure that cannot be ignored.",
                    mandatorySignals: ["Misjudgment", "reverse", "Recycling on the spot"],
                    antiSignals: ["Only beaten but not recycled", "Recycling is too light and not fun"],
                }),
            },
            {
                id: "story_mode_misread",
                name: "Misread Reputation",
                description: "Create fun and excitement around other people's misunderstanding of the protagonist, active brainstorming, and out-of-control amplification.",
                template: "Misunderstandings will be magnified layer by layer and constantly turn into a situation that is beneficial to the protagonist.",
                profile: buildProfile({
                    coreDrive: "Use others' over-interpretation of the protagonist to create an advantageous situation that continues to get out of control.",
                    readerReward: "Readers repeatedly get the contrasting pleasure of \"other people's own imagination is too much\".",
                    progressionUnits: ["misread", "Brain supplement upgrade", "group diffusion", "Misunderstanding cashed out"],
                    allowedConflictForms: ["information asymmetry", "chain of misunderstandings", "group interpretation bias"],
                    forbiddenConflictForms: ["explain clearly directly", "A misunderstanding only lasts once and ends"],
                    conflictCeiling: "medium",
                    resolutionStyle: "Let the misunderstanding grow naturally and turn into resources or reputation for the protagonist.",
                    chapterUnit: "A single chapter revolves around an escalation of misunderstanding and unexpected gains.",
                    volumeReward: "The misreading system at the end of the volume forms a stable consensus or legendary image.",
                    mandatorySignals: ["Brainstorming", "Out of control spread", "The protagonist passively benefits"],
                    antiSignals: ["Misunderstanding and force", "Everyone sees through it quickly"],
                }),
            },
            {
                id: "story_mode_secret_identity",
                name: "Hidden Identities",
                description: "Use multiple identities, hidden layers and the risk of losing horses to drive the desire to read.",
                template: "The vests must have their own functions, and the risk of losing the horse must form a continuous hook.",
                profile: buildProfile({
                    coreDrive: "Continuous tension is created through multiple identity switching, hiding and risk of losing one's horse.",
                    readerReward: "Readers constantly see the thrill of identity differences, information gaps, and the edge of falling off the horse.",
                    progressionUnits: ["Create a vest", "switch identity", "Almost fell off the horse", "Cash out"],
                    allowedConflictForms: ["Identity hidden", "Dislocation of relationship", "Misjudgment of the source of ability"],
                    forbiddenConflictForms: ["All vest functions are repeated", "There are no consequences for falling off the horse"],
                    conflictCeiling: "medium",
                    resolutionStyle: "Solve the problem around identity switching, and then transfer the pressure to the next level of risk of losing your horse.",
                    chapterUnit: "A single chapter advances identity exploitation or risk approximation at least once.",
                    volumeReward: "The end of the volume forms a critical fall or a more complex web of identity.",
                    mandatorySignals: ["information gap", "Identity switching", "hook"],
                    antiSignals: ["Identity line remains static for a long time", "The vest just has a different name and has no purpose."],
                }),
            },
        ],
    },
    {
        id: "story_mode_build_root",
        name: "Building and Management",
        description: "A reading model with accumulation, construction, operation and staged harvest as the main promotion methods.",
        template: "Let the world become richer, more stable, and more rewarding as the protagonist takes action.",
        profile: buildProfile({
            coreDrive: "Continuously create a sense of accomplishment through accumulation, expansion, management and construction results.",
            readerReward: "Readers can see the satisfaction of more resources, more stable territory, and more complete systems.",
            progressionUnits: ["Accumulate resources", "Construction node", "Business upgrade", "staged harvest"],
            allowedConflictForms: ["Resource pressure", "business competition", "development obstacles"],
            forbiddenConflictForms: ["The villains have long overpowered the main line of construction", "It all depends on the war to advance"],
            conflictCeiling: "medium",
            resolutionStyle: "Prioritize using operations, organization, construction and resource scheduling to resolve problems.",
            chapterUnit: "Each chapter advances a visible operating or construction unit.",
            volumeReward: "The end of the volume gives a more stable, larger, and richer picture of the results.",
            mandatorySignals: ["accumulate", "construction process", "Achievements display"],
            antiSignals: ["The main drive becomes a pure combat text", "No harvest will be seen for a long time"],
        }),
        children: [
            {
                id: "story_mode_farming",
                name: "Homestead Growth",
                description: "A constructive model that values \u200B\u200Bproduction, accumulation, order in life and a sense of long-term recovery.",
                template: "Focus on resource circulation, land or stronghold management, relationship maturation and staged harvests.",
                profile: buildProfile({
                    coreDrive: "By revitalizing life and production bit by bit, it gives readers a stable sense of recovery and accumulation.",
                    readerReward: "Readers continue to gain the satisfaction of \"life is getting better and better\" and \"their family wealth is getting stronger and stronger\".",
                    progressionUnits: ["Sowing preparation", "production accumulation", "neighborhood interaction", "Cashing in the harvest"],
                    allowedConflictForms: ["resource shortage", "Weather and environmental stress", "Small-scale interest friction"],
                    forbiddenConflictForms: ["Long-term high voltage life and death line", "Endless villain plot"],
                    conflictCeiling: "low",
                    resolutionStyle: "Problems are slowly solved through hard work, organization, mutual assistance and management.",
                    chapterUnit: "A single chapter revolves around a piece of work, a piece of construction, or a period of life improvement.",
                    volumeReward: "The end of the volume forms a noticeably more stable and warmer phase of life.",
                    mandatorySignals: ["sense of life", "work details", "stage harvest"],
                    antiSignals: ["Only fighting monsters and conspiracy are left", "No improvement in life seen"],
                }),
            },
            {
                id: "story_mode_management",
                name: "Enterprise Management",
                description: "Use business, organization, brand or system operations to promote the plot.",
                template: "Emphasize decision-making, operations, expansion, word-of-mouth and staged business results.",
                profile: buildProfile({
                    coreDrive: "Continuously create a sense of upward mobility through business decisions and organizational expansion.",
                    readerReward: "Readers repeatedly see businesses take off, organizations take shape, and word-of-mouth grow.",
                    progressionUnits: ["find a breakthrough", "Build process", "Expand scale", "win the market"],
                    allowedConflictForms: ["business competition", "Resource allocation", "Team run-in"],
                    forbiddenConflictForms: ["Irrelevant love affairs steal the show for a long time", "The business process was briefly reviewed"],
                    resolutionStyle: "Rely on strategy, operations, division of labor and rhythm management to solve problems.",
                    chapterUnit: "A single chapter advances a business action or organizational issue.",
                    volumeReward: "At the end of the volume, business upgrades, brand establishment, or organizational transitions will occur.",
                    mandatorySignals: ["Sense of strategy", "Business actions", "Results feedback"],
                    antiSignals: ["Only talk about the results and not the process", "The main business line is eaten up by the villain line"],
                }),
            },
            {
                id: "story_mode_territory_building",
                name: "Settlement Building",
                description: "Continue to advance around strongholds, towns, power territory and order construction.",
                template: "Focus on territory upgrading, population gathering, rule establishment and defense line stabilization.",
                profile: buildProfile({
                    coreDrive: "By gradually building a piece of land, a city or a stronghold into shape, you can continue to create a sense of expansion and stability.",
                    readerReward: "Readers continue to see the territory become stronger, order taking shape, and security increasing.",
                    progressionUnits: ["Recruitment and Placement", "Facility construction", "Rules implemented", "External test response"],
                    allowedConflictForms: ["Resources are tight", "boundary friction", "manage stress", "security crisis"],
                    forbiddenConflictForms: ["The territory has been in name only for a long time", "The main plot was completely taken away by purely personal grudges"],
                    conflictCeiling: "medium",
                    resolutionStyle: "Prioritize stabilizing the situation through construction, governance, organization and local countermeasures.",
                    chapterUnit: "A single chapter advances a territory's construction actions, governance issues, or responses to external temptations.",
                    volumeReward: "At the end of the volume, there is a clear jump in the size, order, or influence of the territory.",
                    mandatorySignals: ["Stronghold growth", "governance actions", "order taking shape"],
                    antiSignals: ["Only war without construction", "The sense of territorial presence is getting weaker and weaker"],
                }),
            },
            {
                id: "story_mode_family_management",
                name: "Family Legacy",
                description: "Family business, family relationships, and intergenerational responsibility drive continued reading.",
                template: "Describe resource management, family division of labor and internal relationship changes together.",
                profile: buildProfile({
                    coreDrive: "Maintain story advancement through family business expansion, family relationship reorganization, and responsibility inheritance.",
                    readerReward: "Readers can not only see that the family fortune has become thicker, but also that the relationships between family members are becoming more and more systematic.",
                    progressionUnits: ["Family business adjustment", "Members get in touch", "Resource accumulation", "Improvement of family status"],
                    allowedConflictForms: ["Housework disagreements", "Distribution of benefits", "external competition", "conflict of ideas between generations"],
                    forbiddenConflictForms: ["The bloody tear has overwhelmed the business line for a long time", "Family members only have tool functions and no relationship changes."],
                    conflictCeiling: "medium",
                    resolutionStyle: "Restoration is accomplished through negotiation, division of labor, business results, and joint response to crises.",
                    chapterUnit: "A single chapter advances a family business action, a family interaction or the fulfillment of a responsibility.",
                    volumeReward: "At the end of the volume, the family becomes more stable and cohesive, or a status jump is achieved.",
                    mandatorySignals: ["family collaboration", "Family business action", "relationship reorganization"],
                    antiSignals: ["Only quarrels and no management left", "There is no sense of inheritance in the family line"],
                }),
            },
        ],
    },
    {
        id: "story_mode_healing_root",
        name: "Everyday Healing",
        description: "It is driven by companionship, restoration, life recovery and low-intensity continuous companionship.",
        template: "Conflicts are allowed, but they cannot destroy the sense of warmth and companionship.",
        profile: buildProfile({
            coreDrive: "It continues to captivate readers through companionship, restoration, life details, and relationship renewal.",
            readerReward: "Readers repeatedly gain a sense of stability, tenderness, warmth, and emotional satisfaction.",
            progressionUnits: ["daily life", "Accompanying repair", "Small problem solving", "Warming up of relationship"],
            allowedConflictForms: ["low to moderate intensity dilemma", "relational error", "life pressure"],
            forbiddenConflictForms: ["Continuous high-pressure confrontation", "Blackened advancement", "Endless backstabbing"],
            conflictCeiling: "low",
            resolutionStyle: "Prioritize resolving problems through companionship, understanding, daily actions and small-scale repairs.",
            chapterUnit: "Each chapter revolves around a life episode or emotional repair point.",
            volumeReward: "At the end of the volume, readers feel that the characters are in a more stable, warmer state, and more willing to continue living.",
            mandatorySignals: ["sense of life", "Be comforted", "relations warm up"],
            antiSignals: ["High voltage main line dominates the scene", "The sense of healing is continuously interrupted"],
        }),
        children: [
            {
                id: "story_mode_healing_daily",
                name: "Restorative Everyday Life",
                description: "A healing model that focuses on daily interaction, companionship, and emotional recovery.",
                template: "Keep the intensity of dilemmas low and the density of comfort points high so readers will want to stay.",
                profile: buildProfile({
                    coreDrive: "Rely on daily companionship and small repairs to slowly bring the character back to a stable state.",
                    readerReward: "The reader gets an emotionally soothing experience every few chapters.",
                    progressionUnits: ["daily interactions", "Emotional soothing", "Relationship maturation", "life improvement"],
                    allowedConflictForms: ["Little setbacks in life", "Awkward relationship", "Echoes of old wounds"],
                    forbiddenConflictForms: ["The villain dominates", "Long-term extreme pain without recovery"],
                    conflictCeiling: "low",
                    resolutionStyle: "Let the characters be cured little by little through companionship, listening and specific actions.",
                    chapterUnit: "Each chapter revolves around an emotional node and a comfort point.",
                    volumeReward: "At the end of the volume, both the characters and the readers feel that their condition has improved significantly.",
                    mandatorySignals: ["sense of comfort", "life details", "Gentle interaction"],
                    antiSignals: ["Conflict escalates into high-voltage drama", "After reading a chapter, only anxiety remains"],
                }),
            },
            {
                id: "story_mode_shop_daily",
                name: "Small-Business Life",
                description: "Store management and people-to-people interactions form a stable and healing rhythm of reading.",
                template: "Customers, neighbors, and business chores should all be gentle nudges.",
                profile: buildProfile({
                    coreDrive: "Create a continuous sense of freshness through store operations, customer stories and community interaction.",
                    readerReward: "Readers can not only see business changes, but also get warm stories from strangers.",
                    progressionUnits: ["guest event", "Operational adjustments", "community interaction", "Daily practice"],
                    allowedConflictForms: ["Small store operating pressure", "Friendly relationship", "trivial matters of life"],
                    forbiddenConflictForms: ["Continuous vicious suppression", "Heavy suspense or high-pressure conspiracy-led"],
                    resolutionStyle: "It can be resolved naturally through hospitality, business adjustments and community mutual assistance.",
                    chapterUnit: "Each chapter promotes a guest interaction or small business event.",
                    volumeReward: "The end of the paper makes the shop more popular and has a sense of belonging.",
                    mandatorySignals: ["The sense of space in a small store", "Guest stories", "community temperature"],
                    antiSignals: ["All that's left is business data, which is impersonal.", "Store presence is getting weaker and weaker"],
                }),
            },
            {
                id: "story_mode_slow_life",
                name: "Slow Living",
                description: "The slowed down pace, details of life and restoration of daily order constitute the attraction of reading.",
                template: "Let the scenery, work, food, and ways of being together become part of the experience of stability.",
                profile: buildProfile({
                    coreDrive: "Readers are driven to stay by the slow but constant sense of life improvement and physical and mental peace.",
                    readerReward: "Readers are repeatedly left with a sense of relaxation, immersion, and the satisfaction of 'finally slowing down'.",
                    progressionUnits: ["daily routine", "Familiar environment", "life improvement", "Emotions stabilized"],
                    allowedConflictForms: ["Slightly uncomfortable", "Little troubles in life", "Adjustment after estrangement"],
                    forbiddenConflictForms: ["Continuous high pressure countdown", "A strong villain pursues him for a long time or suppresses a conspiracy"],
                    conflictCeiling: "low",
                    resolutionStyle: "Slowly resolve problems through time, companionship, routine, and small repair steps.",
                    chapterUnit: "A single chapter revolves around a slice of life, a small improvement, or an emotional buffer.",
                    volumeReward: "At the end of the volume, the characters truly have a more stable and comfortable life state.",
                    mandatorySignals: ["life order", "Relaxation", "Immersive details"],
                    antiSignals: ["In order to stimulate frequent violent conflicts,", "The rhythm is getting more and more restless and there is no sense of breathing"],
                }),
            },
            {
                id: "story_mode_companion_healing",
                name: "Companionship and Recovery",
                description: "Take stable companionship, care and joint recovery between people as the main thrust.",
                template: "Contradictions should serve proximity, trust and repair, rather than continuous tearing apart.",
                profile: buildProfile({
                    coreDrive: "Through the gradual establishment of a companionship relationship and the gradual accumulation of a sense of security, emotions can be realized.",
                    readerReward: "Readers constantly gain the gentle satisfaction of being understood and being accompanied through the troughs.",
                    progressionUnits: ["approach and probing", "daily care", "Emotional looseness", "Relationship confirmation"],
                    allowedConflictForms: ["Avoidance of old wounds", "communication lag", "life pressure", "brief misunderstanding"],
                    forbiddenConflictForms: ["Repeated backstabbing", "Damn it, don\u2019t recycle it for a long time", "Relationships are viciously pulled out of control"],
                    conflictCeiling: "low",
                    resolutionStyle: "Restoration is accomplished with patience, companionship, behavioral support, and emotional responsiveness.",
                    chapterUnit: "A single chapter advances an act of companionship, a loosening of a relationship, or an emotional landing.",
                    volumeReward: "The end of the volume heats up the key relationships significantly, with the characters more willing to trust others and life.",
                    mandatorySignals: ["sense of companionship", "Trust grows", "Repair landing"],
                    antiSignals: ["The healing line suddenly turns into sadomasochistic pulling", "The companionship relationship has not been substantially advanced"],
                }),
            },
        ],
    },
    {
        id: "story_mode_comedy_root",
        name: "Comedy in Motion",
        description: "Contrast, baggage, misunderstanding and out-of-control recycling constitute the main motivation for reading.",
        template: "Relaxation is not a tone label, but a laughter mechanism that continues to be realized in the chapter structure.",
        profile: buildProfile({
            coreDrive: "Continuously create a sense of relaxation and refreshment through contrasts, burdens, misunderstandings and the rhythm of life.",
            readerReward: "Readers frequently get laughs, counter-plots, and emotional stress relief experiences.",
            progressionUnits: ["Set up baggage", "Misunderstanding upgrade", "Contrast recycling", "The situation is out of control"],
            allowedConflictForms: ["misunderstanding", "Contrast", "social death", "Turn over"],
            forbiddenConflictForms: ["Long, heavy and depressive lines have been dominant for a long time", "The joke is not recycled"],
            conflictCeiling: "medium",
            resolutionStyle: "Release is achieved through baggage recovery and out-of-control scenes.",
            chapterUnit: "Each chapter must advance at least one effective laugh structure.",
            volumeReward: "At the end of the volume, a larger whole-name scene or a community of misunderstandings is formed.",
            mandatorySignals: ["Contrast", "Recycle", "easy release"],
            antiSignals: ["Be serious and burdenless for a long time", "The jokes are only made up of tongue-in-cheeks and jokes"],
        }),
        children: [
            {
                id: "story_mode_comedy",
                name: "Situational Comedy",
                description: "High-frequency laughter, contrast and easy recycling are the core of reading.",
                template: "The laugh points must appear in a structured way and cannot just rely on scattered golden sentences.",
                profile: buildProfile({
                    coreDrive: "It relies on high-frequency baggage, contrast and out-of-control scenes to maintain reading pleasure.",
                    readerReward: "Readers will find clear moments of levity and good humor in every chapter.",
                    progressionUnits: ["baggage laying", "Contrast upgrade", "Laughter recycling", "The scene turned upside down"],
                    allowedConflictForms: ["misunderstanding", "social death", "identity contrast", "cognitive dislocation"],
                    forbiddenConflictForms: ["Long term heavy pain line", "The humor is thin and does not advance the plot."],
                    resolutionStyle: "Use recycling and upgrading to continue to increase the humor instead of turning heavy.",
                    chapterUnit: "Each chapter revolves around at least one valid baggage closed loop.",
                    volumeReward: "At the end of the volume, an iconic scene or a joke that continues to circulate is formed.",
                    mandatorySignals: ["baggage", "Recycle", "sense of spectacle"],
                    antiSignals: ["The whole paragraph is serious", "Just complaints and no structure"],
                }),
            },
            {
                id: "story_mode_misunderstanding_comedy",
                name: "Escalating Misunderstanding",
                description: "Create continuous comedy effects by relying on multiple information gaps and the spread of misunderstandings.",
                template: "Misunderstandings will be magnified layer by layer, but each time they will bring about a new situation.",
                profile: buildProfile({
                    coreDrive: "The comic rhythm is maintained through the spread of misunderstandings caused by information gaps among multiple parties.",
                    readerReward: "Readers continually see the effect of misunderstandings growing larger and more interesting.",
                    progressionUnits: ["misunderstanding established", "Many misunderstandings", "uncontrolled spread", "comedy recycling"],
                    allowedConflictForms: ["misunderstanding", "Misplaced communication", "collective misreading"],
                    forbiddenConflictForms: ["Misunderstanding clarified too quickly", "Misunderstanding is just repeating the same story"],
                    resolutionStyle: "Let the misunderstanding be recycled in the funniest position, or upgraded into a bigger laugh point.",
                    chapterUnit: "Each chapter advances a new level of misunderstanding or recycling node.",
                    volumeReward: "At the end of the volume, there is a famous scene of large-scale misunderstanding.",
                    mandatorySignals: ["information gap", "misread", "spread"],
                    antiSignals: ["Misunderstanding has no staying power", "Clarifying too quickly causes the rhythm to stall"],
                }),
            },
            {
                id: "story_mode_absurd_subversion",
                name: "Expectation Reversal",
                description: "Use outrageous expansion, anti-routine recycling and sudden changes in rhythm to create a strong sense of relaxation.",
                template: "Counter-routines not only dismantle expectations, but also continue to provide new and more interesting situations.",
                profile: buildProfile({
                    coreDrive: "Maintain freshness by constantly dismantling conventional expectations and then giving more outrageous but more established results.",
                    readerReward: "Readers continue to get the surprise and sense of relief that \"it's still possible to do this\".",
                    progressionUnits: ["Build expectations", "suddenly twist", "Outrageous upgrade", "Anti-routine recycling"],
                    allowedConflictForms: ["Contrast", "Dislocation", "Life is out of control", "Set jokes"],
                    forbiddenConflictForms: ["Nothing but meaningless madness", "Outrageous but without a logical pivot", "Continuous heavy drama"],
                    conflictCeiling: "medium",
                    resolutionStyle: "Reclaim the situation through a higher level of counter-routine rather than falling back into heavy orthodox conflict.",
                    chapterUnit: "Each chapter advances at least one closed loop of expectation building and anti-routine recycling.",
                    volumeReward: "At the end of the volume, a highly viral and outrageous famous scene or anti-routine climax is formed.",
                    mandatorySignals: ["Sense of surprise", "Counter routine", "Recycling closed loop"],
                    antiSignals: ["Sacrifice readability for fun", "The stacking of jokes does not advance the story"],
                }),
            },
        ],
    },
    {
        id: "story_mode_mystery_root",
        name: "Mystery and Strategy",
        description: "Reading is driven by intellectual satisfaction based on information gaps, deductions, layouts and confrontations.",
        template: "Readers should continue to feel that they are moving toward deeper truths.",
        profile: buildProfile({
            coreDrive: "Through information gaps, deductions and game upgrades, we continue to create the desire to pursue.",
            readerReward: "Readers are constantly satisfied with the advancement of puzzles, the pleasure of reasoning and the recycling of layouts.",
            progressionUnits: ["cast doubt", "Collect clues", "Deduction verification", "reversal of the situation"],
            allowedConflictForms: ["information gap", "Hidden motives", "intellectual confrontation"],
            forbiddenConflictForms: ["Deliberately unreasonable in order to keep confidentiality", "Pure physical confrontation eats up the sense of deduction"],
            conflictCeiling: "high",
            resolutionStyle: "Complete countermeasures through evidence chain, deduction and layout.",
            chapterUnit: "Each chapter advances a new doubt or the verification of an old doubt.",
            volumeReward: "At the end of the volume, a greater truth is revealed or a key game is completed.",
            mandatorySignals: ["clues", "deduction", "Counterattack"],
            antiSignals: ["Mysteries pile up", "The answer comes from heaven"],
        }),
        children: [
            {
                id: "story_mode_mystery_inference",
                name: "Mystery Investigation",
                description: "The core of reading is composed of clues, inferences and truth-revealing rhythms.",
                template: "Each deduction must be based on clear clues and should not be forced upon by the author.",
                profile: buildProfile({
                    coreDrive: "Let readers follow clues and deductions to get closer to the truth.",
                    readerReward: "The reader continues to gain the intellectual satisfaction of 'the puzzle is taking shape'.",
                    progressionUnits: ["raise doubts", "additional clues", "End of deduction", "uncover the truth"],
                    allowedConflictForms: ["Clue conflict", "Contradictory testimony", "Hidden motives"],
                    forbiddenConflictForms: ["Key evidence appears out of thin air", "Deliberately vague to delay"],
                    resolutionStyle: "Break through the situation through clue linkage and logical deduction.",
                    chapterUnit: "Each chapter advances the cognitive change of a key doubt point.",
                    volumeReward: "At the end of the volume, the core mystery is revealed or the entrance to greater suspense is opened.",
                    mandatorySignals: ["sense of clues", "logical chain", "The truth is approaching"],
                    antiSignals: ["Mysterious", "The conclusion is disconnected from the clues"],
                }),
            },
            {
                id: "story_mode_mind_game",
                name: "Contest of Wits",
                description: "Emphasis on layout, game play, opponent thinking and counter-rhythm.",
                template: "The opponent must resemble the opponent and the game must be perceivable.",
                profile: buildProfile({
                    coreDrive: "Through multiple rounds of layout and demolition, a high-viscosity battle of wits is created.",
                    readerReward: "Readers constantly see calculations, counter-calculations, and prejudgment recycling.",
                    progressionUnits: ["Layout", "test", "Counterattack", "Close the net"],
                    allowedConflictForms: ["strategic confrontation", "psychological game", "Resource calculation"],
                    forbiddenConflictForms: ["Opponent is too stupid", "All victory depends on the protagonist cheating information"],
                    resolutionStyle: "Win the situation through early planning and key counterattacks.",
                    chapterUnit: "Each chapter advances a round of trials, traps or demolition moves.",
                    volumeReward: "At the end of the volume, a large-scale closing of the net is completed or a higher-level opponent appears.",
                    mandatorySignals: ["sense of layout", "Opponent pressure", "Counter-recycling"],
                    antiSignals: ["There is no game process in winning or losing", "Adversary instrumentalization"],
                }),
            },
            {
                id: "story_mode_survival_game",
                name: "Survival Challenge",
                description: "Create constant tension within limited resources, high-pressure environments, and rule-based competition.",
                template: "High pressure can exist, but it must serve the purpose of deducing rules, determining costs, and countering situations.",
                profile: buildProfile({
                    coreDrive: "Confrontation through resource scarcity, environmental pressures, and rules continues to create tension in which choices must be made.",
                    readerReward: "Readers repeatedly get the intense satisfaction of situation resolution, cost weighing and desperate comeback.",
                    progressionUnits: ["Pressure is approaching", "Rule heuristics", "Competition for resources", "Short-term countermeasures"],
                    allowedConflictForms: ["Scarce resources", "Rule oppression", "environmental threats", "group game"],
                    forbiddenConflictForms: ["Complete the level purely by luck", "Only hand-to-hand combat without strategy", "Repeating the same crisis over a long period of time"],
                    conflictCeiling: "high",
                    resolutionStyle: "Rely on rule understanding, situation judgment and limited resource allocation to break the situation.",
                    chapterUnit: "A single chapter advances a round of survival pressure, rule discovery or key choices.",
                    volumeReward: "At the end of the volume, successfully complete a stage of survival, break through the rules, or rewrite the camp pattern.",
                    mandatorySignals: ["Resource pressure", "choice price", "Rule utilization"],
                    antiSignals: ["cheapening of crisis", "It's always the same dilemma cycle"],
                }),
            },
        ],
    },
    {
        id: "story_mode_relationship_root",
        name: "Relationships and Emotion",
        description: "The main driving force is relationship promotion, emotional realization and the pull and change between characters.",
        template: "The point is not to simply pile up conflicts, but to keep the relationship status changing and fulfill the readers' expectations.",
        profile: buildProfile({
            coreDrive: "Through the closeness, pull, dislocation and recycling of character relationships, we continue to create motivation for reading.",
            readerReward: "Readers are constantly provided with relationship changes, emotional tension, and key mood realizations.",
            progressionUnits: ["relationship building", "Emotional pull", "Trust changes", "Node cashing out"],
            allowedConflictForms: ["relational error", "emotional dislocation", "realistic resistance", "Value friction"],
            forbiddenConflictForms: ["The relationship line is stagnant for a long time", "Meaningless blood swirls over and over again", "Emotional advancement has been swallowed up by other lines for a long time"],
            conflictCeiling: "medium",
            resolutionStyle: "Advancement or repair is accomplished through emotional communication, relational action, and critical choices.",
            chapterUnit: "Each chapter advances a relationship node, emotional change, or mutual perception change.",
            volumeReward: "At the end of the volume, a clear change occurs in a key relationship or a high-value emotional realization is completed.",
            mandatorySignals: ["relationship tension", "emotional node", "Sense of redemption"],
            antiSignals: ["The relationship remains unchanged", "Only settings and no interaction"],
        }),
        children: [
            {
                id: "story_mode_romantic_tension",
                name: "Romantic Tension",
                description: "Use ambiguity, approach, withdrawal and relationship testing to create continuous attraction.",
                template: "There must be a temperature difference and propulsion in pulling, and we cannot rely solely on misunderstandings to delay it.",
                profile: buildProfile({
                    coreDrive: "Emotional tension is maintained through the repeated pull between two-way attraction and realistic resistance.",
                    readerReward: "Readers constantly see relationships heating up, temptations spiraling out of control, and emotions recycling.",
                    progressionUnits: ["Tentatively approaching", "boundary collision", "emotional imbalance", "relationship advancement"],
                    allowedConflictForms: ["Ambiguity and dislocation", "Expression failure", "realistic resistance", "Value differences"],
                    forbiddenConflictForms: ["Deliberately trying not to speak human words", "Delayed for too long without progress", "The relationship line is completely suppressed by the external main line"],
                    conflictCeiling: "medium",
                    resolutionStyle: "Relationship advancement is accomplished through interaction escalation, emotional acknowledgment, and action selection.",
                    chapterUnit: "A single chapter advances an emotional trial, cognitive change, or loosening of relationship boundaries.",
                    volumeReward: "At the end of the paper, the relationship enters a new stage, or a high-concentration emotional confirmation is completed.",
                    mandatorySignals: ["Ambiguity", "Two-way tension", "Close to cashing out"],
                    antiSignals: ["Only misunderstanding delays", "No substantial relationship changes"],
                }),
            },
            {
                id: "story_mode_chasing_wife",
                name: "Relationship Repair",
                description: "It is based on the premise of early injury or mistake and relies on subsequent recovery, regret and relationship reconstruction to advance.",
                template: "The core is recovery and reconstruction, not unilateral repeated harm.",
                profile: buildProfile({
                    coreDrive: "Create strong emotional pull through recovery, repentance, and relationship reconstruction after loss.",
                    readerReward: "Readers continue to get the satisfaction of \"catching up what should be pursued, returning what should be returned, and responding to what should be painful.\"",
                    progressionUnits: ["Regret appears", "recovery action", "relationship trials", "rebuild cash"],
                    allowedConflictForms: ["trust broken", "Fighting back from old wounds", "Compensation gap", "Realistic obstacles"],
                    forbiddenConflictForms: ["Compensation is just words", "Infinite loop of secondary damage", "The party being pursued completely loses their subjectivity"],
                    conflictCeiling: "medium",
                    resolutionStyle: "Promote relationship reconstruction through sustained action, cost sharing, and boundary respect.",
                    chapterUnit: "A single chapter advances a recovery action, a collision of old injuries, or a loosening of a relationship.",
                    volumeReward: "The end of the volume leads to a clear phase of relationship repair or powerful emotional recycling.",
                    mandatorySignals: ["Regret falls on the ground", "action compensation", "border reconstruction"],
                    antiSignals: ["Only verbal apology", "There is no cost to rebuilding a relationship"],
                }),
            },
            {
                id: "story_mode_ensemble_bond",
                name: "Ensemble Bonds",
                description: "Reading stickiness is formed through the evolution of multi-person relationships, shared experiences and bonds.",
                template: "A group portrait is not a list of people, but each role must play a role in the relationship network.",
                profile: buildProfile({
                    coreDrive: "Through multi-person interaction and bond changes, the story always has new relationship sparks.",
                    readerReward: "Readers are continually provided with new connections, shifts in alignment, and emotional resonance between characters.",
                    progressionUnits: ["Relationship series", "mass incident", "position change", "The bond deepens"],
                    allowedConflictForms: ["Differences in stance", "Differences in responsibility", "emotional dislocation", "team pressure"],
                    forbiddenConflictForms: ["Long-term instrumentalization of group portrait roles", "Only the protagonist is left alone", "The relationship network does not change"],
                    conflictCeiling: "medium",
                    resolutionStyle: "Relationships evolve through team interactions, shared experiences, and choices between roles.",
                    chapterUnit: "A single chapter advances a group interaction node or a change in the relationship between a key character pair.",
                    volumeReward: "The end of the volume makes the group structure more stable, or allows the team/relationship network to enter a new stage.",
                    mandatorySignals: ["group interaction", "Relationship linkage", "Characters make each other successful"],
                    antiSignals: ["The role only tells the name but does not do any work", "The group portrait breaks into a one-man show"],
                }),
            },
        ],
    },
    {
        id: "story_mode_growth_root",
        name: "Growth and Adventure",
        description: "Upgrading, exploration, breakthroughs and staged breakthroughs constitute the main driving force for reading.",
        template: "Readers need to continually sense that the character's abilities, cognition, or world boundaries are expanding.",
        profile: buildProfile({
            coreDrive: "Continuously create a sense of progress through growth curves, exploration advancement and stage breakthroughs.",
            readerReward: "Readers are repeatedly given the satisfaction of becoming stronger, unlocking new areas, and reaching new thresholds.",
            progressionUnits: ["get target", "Challenge Escalation", "Break through bottlenecks", "Enter new area"],
            allowedConflictForms: ["Trial", "explore risks", "stage threshold", "growing pains"],
            forbiddenConflictForms: ["Long-term stagnation without growth", "Only the upgrade value does not change the experience", "Discovery line long absent"],
            conflictCeiling: "high",
            resolutionStyle: "Complete the breakthrough through training, practice, exploration and staged breakthroughs.",
            chapterUnit: "Each chapter advances a growth action, an exploration and discovery, or a period of feedback for level breakthrough.",
            volumeReward: "At the end of the volume, the character reaches a higher stage or opens up a larger adventure space.",
            mandatorySignals: ["sense of growth", "Sense of breakthrough", "world expansion"],
            antiSignals: ["Upgrade verbalization", "Adventure line suspended"],
        }),
        children: [
            {
                id: "story_mode_growth_leveling",
                name: "Progressive Growth",
                description: "The pleasure of reading is built around character abilities, cognition, and stage threshold breakthroughs.",
                template: "When upgrading, you not only write down the results, but also write down the threshold, price and redemption.",
                profile: buildProfile({
                    coreDrive: "Continuously drive reading through clear and tangible growth curves and stage breakthroughs.",
                    readerReward: "Readers constantly see substantial increases in ability, status, or cognitive level.",
                    progressionUnits: ["accumulation conditions", "stuck point blocked", "complete breakthrough", "show improvement"],
                    allowedConflictForms: ["bottleneck", "Trial", "Insufficient resources", "Competition at the same level"],
                    forbiddenConflictForms: ["Growth depends entirely on narration. Skip it", "There is no price or preparation for breakthrough", "Nothing is redeemed after the upgrade"],
                    conflictCeiling: "high",
                    resolutionStyle: "Achieve growth breakthroughs through accumulation, training, actual combat and key insights.",
                    chapterUnit: "A single chapter advances an accumulation, a stuck point trial or a growth realization.",
                    volumeReward: "Complete a clear level, realm or stage transition at the end of the volume.",
                    mandatorySignals: ["growth threshold", "Breakthrough feedback", "Stage changes"],
                    antiSignals: ["Upgrading is like a running account", "Ability improvement has no plot consequences"],
                }),
            },
            {
                id: "story_mode_adventure_exploration",
                name: "Exploration Adventure",
                description: "New maps, new civilizations and unknown risks drive the freshness of reading.",
                template: "Exploration brings truly new information, new choices, and new dangers.",
                profile: buildProfile({
                    coreDrive: "Keep your reading fresh by constantly venturing into unknown territories, encountering new rules, and discovering new secrets.",
                    readerReward: "Readers continue to gain insights, discoveries, and a sense of the unknown.",
                    progressionUnits: ["Enter new area", "discover new rules", "encounter risks", "bring out new knowledge"],
                    allowedConflictForms: ["environmental threats", "unknown rules", "Explore competition", "Civilization differences"],
                    forbiddenConflictForms: ["The scene is just a reskin", "Exploration yields no new information", "Staying where you are without pushing the boundaries of the world"],
                    conflictCeiling: "high",
                    resolutionStyle: "Unlock deeper exploration through observation, response, adaptation, and local breakthroughs.",
                    chapterUnit: "A single chapter advances a new discovery, an environmental response, or a map exploration.",
                    volumeReward: "The end of the volume opens new area levels, secret entrances, or adventure objectives.",
                    mandatorySignals: ["sense of unknown", "sense of discovery", "map extension"],
                    antiSignals: ["Explore idling", "The new area has no meaning"],
                }),
            },
            {
                id: "story_mode_dungeon_challenge",
                name: "Trial-Based Progression",
                description: "It uses stage levels, rule cracking and clearance feedback to form a strong rhythm.",
                template: "The dungeon is not about repeatedly defeating monsters. The goals, mechanisms, risks and rewards for clearing the level must be written clearly.",
                profile: buildProfile({
                    coreDrive: "Through staged level challenges and rule cracking, a continuous thrill of advancement is formed.",
                    readerReward: "Readers constantly get the satisfaction of passing levels, breaking games, and cashing in rewards.",
                    progressionUnits: ["Enter the copy", "recognition mechanism", "Breaking the Difficulties", "Customs clearance and settlement"],
                    allowedConflictForms: ["Level mechanics", "time pressure", "Team coordination", "Resource limits"],
                    forbiddenConflictForms: ["The copy mechanism relies entirely on hard resistance", "There is no reward feedback after clearing the level", "The copy is so repetitive that it has no new ideas."],
                    conflictCeiling: "high",
                    resolutionStyle: "Complete levels through rule identification, teamwork and key execution.",
                    chapterUnit: "A single chapter advances a level node, a mechanism crack, or a level pass feedback.",
                    volumeReward: "At the end of the volume, complete a complete dungeon journey and receive significant rewards or higher-level entrances.",
                    mandatorySignals: ["sense of mechanism", "Feedback", "Reward redemption"],
                    antiSignals: ["Level homogeneity", "There is only numerical stacking and no mechanism"],
                }),
            },
        ],
    },
];
