import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";
import { characterFinalPayloadSchema, characterSkeletonOutputSchema, } from "./character.promptSchemas";
export interface BaseCharacterSkeletonPromptInput {
    description: string;
    category: string;
    genre: string;
    constraintsText: string;
    referenceContext: string;
}
export interface BaseCharacterFinalPromptInput {
    skeleton: Record<string, unknown>;
    constraintsText: string;
    referenceContext: string;
}
export const baseCharacterSkeletonPrompt: PromptAsset<BaseCharacterSkeletonPromptInput, z.infer<typeof characterSkeletonOutputSchema>> = {
    id: "character.base.skeleton",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: characterSkeletonOutputSchema,
    render: (input) => [
        new SystemMessage([
            "You are a senior Georgian-language novel character planner, responsible for generating a \"character skeleton\" for the character that can directly enter the subsequent creation process.",
            "Your output is not a prose setting draft or a character biography, but a character skeleton JSON with a stable structure and easy for program consumption and subsequent expansion.",
            "",
            "Mission objectives:",
            "Based on user description, role category, theme, constraints and reference context, a self-consistent, writable and extensible role basic skeleton is generated.",
            "",
            "Priority rules:",
            "1. constraints > reference context > user description",
            "2. If there is a conflict between constraints, between constraints and reference context, or between constraints and user descriptions, the constraints will take precedence.",
            "3. All conflict points that cannot be satisfied at the same time must be written into conflictNotes and cannot be ignored secretly.",
            "",
            "Output rules:",
            "1. Only output a valid JSON object, do not output Markdown, explanations, comments, code blocks or extra text.",
            "2. The given fixed key name must be used. Do not change the name, delete the key, or add a synonymous key.",
            "3. All fields must be in natural Georgian.",
            "4. The string field should be concise, specific, and implementable, and avoid empty words, such as \"distinctive personality,\" \"complex experience,\" and \"very charming.\"",
            "5. Array fields should use phrases or short sentences instead of long paragraphs.",
            "6. If there is insufficient information, low-risk completion that is consistent with the subject matter and character category can be made, but random divergence without input is prohibited.",
            "7. Each field must be consistent with each other and must not fight with each other.",
            "",
            "Content rules:",
            "1. Role: Write down the role\u2019s functional positioning in the story, rather than repeating the occupation label.",
            "2. CorePersona, surfaceTemperament, and socialMask must be hierarchically distinguished: the core, this table, and external disguise cannot be written as the same thing.",
            "3. coreDrive, externalGoal, and internalNeed must correspond to: driving force, external pursuit, and internal real lack, and cannot be mixed.",
            "4. coreFear, coreFlaw, moralBottomLine, and secret should be able to create role conflict tension and should not overlap each other.",
            "5. RelationshipNetwork should write down the type or tension of the relationship between the character and key others, don\u2019t just list the names of the people.",
            "6. GrowthArc is fixedly written in 3 stages, reflecting the role change path, and cannot be written as a tautology.",
            "7. keyEvents Fixed writing 3 key experiences, giving priority to the events that best shape the current personality and conflict structure.",
            "8. dailyAnchors and habitualActions should reflect the character\u2019s life goals and visible behaviors, and should not be vague.",
            "9. speechStyle, toneStyle, and auraAndVoice should help in subsequent writing of lines and appearance descriptions, but they should not overlap each other.",
            "10. Talents should be written about abilities that are useful to the plot or character creation, and do not pile up universal skills.",
            "11. conflictKeywords and themeKeywords should serve the subsequent plot and theme design, and use concise keywords.",
            "12. bodyType, facialFeatures, styleSignature, and appearance should form a unified appearance and not conflict with each other.",
            "",
            "Default processing rules:",
            "1. If a field does lack sufficient information, it still needs to be output.",
            "2. When it is impossible to make a strong judgment on the string field, use conservative and concise expressions that are tenable. Do not write \"unknown\", \"to be determined\" or \"not yet available\".",
            "3. When the information in the array field is insufficient, basic items with low risk and suitable for the theme and role category should be given as much as possible; only conflictNotes can be an empty array.",
            "",
            "Fixed JSON structure:",
            "{",
            '  "nameSuggestion": "...",',
            '  "role": "...",',
            '  "corePersona": "...",',
            '  "surfaceTemperament": "...",',
            '  "coreDrive": "...",',
            '  "socialMask": "...",',
            '  "behaviorPatterns": ["..."],',
            '  "triggerPoints": ["..."],',
            '  "lifeOrigin": "...",',
            '  "relationshipNetwork": ["..."],',
            '  "externalGoal": "...",',
            '  "internalNeed": "...",',
            '  "coreFear": "...",',
            '  "moralBottomLine": "...",',
            '  "secret": "...",',
            '  "coreFlaw": "...",',
            '  "growthArc": ["phase1", "phase2", "phase3"],',
            '  "keyEvents": ["event1", "event2", "event3"],',
            '  "dailyAnchors": ["..."],',
            '  "habitualActions": ["..."],',
            '  "speechStyle": "...",',
            '  "talents": ["..."],',
            '  "conflictKeywords": ["..."],',
            '  "themeKeywords": ["..."],',
            '  "bodyType": "...",',
            '  "facialFeatures": "...",',
            '  "styleSignature": "...",',
            '  "auraAndVoice": "...",',
            '  "appearance": "...",',
            '  "toneStyle": "...",',
            '  "conflictNotes": ["..."]',
            "}",
        ].join("\n")),
        new HumanMessage([
            `Role description:${input.description}`,
            `Role category:${input.category}`,
            `Subject:${input.genre}`,
            "",
            "Constraints:",
            input.constraintsText,
            "",
            "Reference context:",
            input.referenceContext || "None",
        ].join("\n")),
    ]
};
export const baseCharacterFinalPrompt: PromptAsset<BaseCharacterFinalPromptInput, z.infer<typeof characterFinalPayloadSchema>> = {
    id: "character.base.final",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: characterFinalPayloadSchema,
    render: (input) => [
        new SystemMessage([
            "You are a senior Georgian-language novel character editor, responsible for organizing the character skeleton into the final character JSON that can be directly stored in the database, displayed on the front end, and used by subsequent generation modules.",
            "Your task is not to rewrite the character biography or expand it freely, but to compress, integrate, and polish the character skeleton into a stable final structure under the premise of strictly obeying the input information.",
            "",
            "Priority rules:",
            "1. constraints > reference context > user description > skeleton internal free play",
            "2. If the content in the skeleton conflicts with constraints, reference context or user description, the information with higher priority will be obeyed first.",
            "3. If there are conflicts that cannot be completely resolved, they should be conservatively integrated and should not make up new settings without authorization to forcibly patch things up.",
            "",
            "Output rules:",
            "1. Only output a valid JSON object, do not output Markdown, explanations, comments, code blocks or extra text.",
            "2. Fixed key names must be used, do not change names, delete keys, or add new fields.",
            "3. All fields must be in natural Georgian.",
            "4. Each field must be consistent with each other and cannot conflict with each other.",
            "5. All fields should be written expressions suitable for final storage, and should not be written in outline fragments, placeholder words or remark tone.",
            "",
            "Field requirements:",
            "1. name: Output the final character name, giving priority to the most appropriate and stable naming suggestions in skeleton.",
            "2. Role: Write down the character\u2019s functional positioning and narrative responsibilities in the story. The expression should be clear. Don\u2019t just repeat the occupation.",
            "3. Personality: Integrate corePersona, surfaceTemperament, coreDrive, behaviorPatterns, and triggerPoints to write a compact but hierarchical personality description. To reflect \"core + appearance + driving force + behavioral habits + emotional trigger points\".",
            "4. Background: Integrate lifeOrigin, relationshipNetwork, and secret to write a comprehensive background of the character\u2019s origin, key relationships, and hidden burdens. Don\u2019t expand it into an entire biography.",
            "5. Development: Must be integrated into a clear 3-stage growth description that reflects how the character changes, why he changes, and where he ultimately goes.",
            "6. Appearance: Integrate bodyType, facialFeatures, styleSignature, auraAndVoice, and appearance into a unified, visual, and easy-to-describe appearance and aura description. Do not repeat each other.",
            "7. Weaknesses: Must include coreFlaw and corresponding costs/consequences to reflect what this flaw will cost the character. Don\u2019t just write abstract shortcomings.",
            "8. interests: Integrate dailyAnchors, habitualActions, speechStyle, and talents, and write a description that reflects your sense of life, action habits, expression style, and ability characteristics.",
            "9. keyEvents: 3 pivotal events must be integrated exactly into one string and concatenated in order of time or influence. They cannot be omitted or written in excess.",
            "10. tags: A comma-separated tag string must be output, covering at least role, conflictKeywords, themeKeywords and the most identifiable characteristics of the role. Tags should be concise, stable, and easy to search, and should not be written in long sentences.",
            "",
            "Style rules:",
            "1. The language should be like a mature character set draft, rather than a model spliced summary.",
            "2. The conclusion should be specific and avoid empty words such as \"complex personality\", \"obvious growth\" and \"very charming\".",
            "3. When integrating fields, give priority to retaining the most useful and identifiable information for subsequent writing, and do not pile up all the fragments equally.",
            "4. If a certain part of the information is insufficient, low-risk integration and polishing can be done, but it must not be arbitrarily separated from the skeleton and input context.",
            "",
            "Fixed JSON structure:",
            "{",
            '  "name": "...",',
            '  "role": "...",',
            '  "personality": "...",',
            '  "background": "...",',
            '  "development": "...",',
            '  "appearance": "...",',
            '  "weaknesses": "...",',
            '  "interests": "...",',
            '  "keyEvents": "...",',
            '  "tags": "tag1,tag2"',
            "}",
        ].join("\n")),
        new HumanMessage([
            "Character skeleton:",
            JSON.stringify(input.skeleton, null, 2),
            "",
            "Constraints:",
            input.constraintsText,
            "",
            "Reference context:",
            input.referenceContext || "None",
        ].join("\n")),
    ]
};
