import type {
  WorldSkeletonGenerationCounts,
  WorldSkeletonPreset,
} from "@ai-novel/shared/types/worldWizard";
import {
  WORLD_SKELETON_COUNT_LIMITS,
  WORLD_SKELETON_PRESET_COUNTS,
} from "@ai-novel/shared/types/worldWizard";
import { Button } from "@/components/ui/button";

const PRESET_CARDS: Array<{
  value: WorldSkeletonPreset;
  title: string;
  description: string;
}> = [
  {
    value: "light",
    title: "Lightweight stage",
    description: "Suitable for short stories, single main line, low complexity, first get a clear and easy-to-write story stage.",
  },
  {
    value: "standard",
    title: "Standard novel",
    description: "Suitable for most long web articles, sufficient rules, forces, locations and opening entrances are generated by default.",
  },
  {
    value: "epic",
    title: "Complex group portrait",
    description: "Suitable for multi-power, multi-location, multi-line conflicts, which require stronger maps and relationships.",
  },
];

const COUNT_LABELS: Record<keyof WorldSkeletonGenerationCounts, string> = {
  rules: "core rules",
  factionGroups: "camp direction",
  forces: "specific forces",
  locations: "key locations",
  conflicts: "relationship/conflict",
  storyEntrySuggestions: "story entrance",
};

interface WorldGeneratorStepTwoProps {
  preset: WorldSkeletonPreset;
  counts: WorldSkeletonGenerationCounts;
  generating: boolean;
  onPresetChange: (preset: WorldSkeletonPreset) => void;
  onCountChange: (key: keyof WorldSkeletonGenerationCounts, value: number) => void;
  onGenerateSkeleton: () => void;
}

export default function WorldGeneratorStepTwo(props: WorldGeneratorStepTwoProps) {
  const {
    preset,
    counts,
    generating,
    onPresetChange,
    onCountChange,
    onGenerateSkeleton,
  } = props;

  return (
    <div className="space-y-4">
      <div className="rounded-md border bg-background p-4">
        <div className="text-sm font-medium">Choose world size</div>
        <div className="mt-1 text-xs text-muted-foreground">
          Scale will determine how many rules, factions, specific forces, key locations, and openable book entrances the AI generates. "Standard Long" is recommended by default.
        </div>
      </div>

      <div className="grid gap-3 md:grid-cols-3">
        {PRESET_CARDS.map((item) => (
          <button
            key={item.value}
            type="button"
            className={`rounded-md border p-4 text-left transition ${
              preset === item.value ? "border-primary bg-primary/5" : "bg-background hover:border-primary/60"
            }`}
            onClick={() => onPresetChange(item.value)}
          >
            <div className="text-sm font-semibold">{item.title}</div>
            <div className="mt-2 text-xs leading-5 text-muted-foreground">{item.description}</div>
            <div className="mt-3 grid grid-cols-2 gap-1 text-xs text-muted-foreground">
              <span>Forces {WORLD_SKELETON_PRESET_COUNTS[item.value].forces}</span>
              <span>Locations {WORLD_SKELETON_PRESET_COUNTS[item.value].locations}</span>
              <span>Conflicts {WORLD_SKELETON_PRESET_COUNTS[item.value].conflicts}</span>
              <span>Entries {WORLD_SKELETON_PRESET_COUNTS[item.value].storyEntrySuggestions}</span>
            </div>
          </button>
        ))}
      </div>

      <div className="rounded-md border p-4">
        <div className="text-sm font-medium">Adjust quantity</div>
        <div className="mt-1 text-xs text-muted-foreground">
          Beginners are advised to keep the default; only adjust it if you clearly want a smaller or larger world.
        </div>
        <div className="mt-4 grid gap-3 md:grid-cols-2">
          {(Object.keys(COUNT_LABELS) as Array<keyof WorldSkeletonGenerationCounts>).map((key) => {
            const limit = WORLD_SKELETON_COUNT_LIMITS[key];
            return (
              <label key={key} className="rounded-md border p-3 text-sm">
                <div className="flex items-center justify-between gap-3">
                  <span className="font-medium">{COUNT_LABELS[key]}</span>
                  <span className="text-xs text-muted-foreground">{counts[key]}</span>
                </div>
                <input
                  className="mt-3 w-full"
                  type="range"
                  min={limit.min}
                  max={limit.max}
                  step={1}
                  value={counts[key]}
                  onChange={(event) => onCountChange(key, Number(event.target.value))}
                />
              </label>
            );
          })}
        </div>
      </div>

      <Button onClick={onGenerateSkeleton} disabled={generating}>
        {generating ? "Generating world skeleton..." : "Generate world skeleton"}
      </Button>
    </div>
  );
}
