import type { WorldReferenceMode } from "@ai-novel/shared/types/worldWizard";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";
import { type WorldAxiomSuggestionPromptInput, type WorldConsistencyPromptInput, type WorldDeepeningQuestionsPromptInput, type WorldImportExtractionPromptInput, type WorldInspirationConceptCardLocalizationPromptInput, type WorldInspirationConceptCardPromptInput, type WorldLayerGenerationPromptInput, type WorldLayerLocalizationPromptInput, type NovelThemeWorldGenerationPromptInput, type WorldPropertyOptionsPromptInput, type WorldReferenceInspirationPromptInput, type WorldStructureBackfillPromptInput, type WorldStructureSectionPromptInput, type WorldVisualizationPromptInput, } from "./world.promptTypes";
import { worldAxiomSuggestionSchema, worldConceptCardSchema, worldConsistencyIssuesSchema, worldDeepeningQuestionsSchema, worldImportExtractionSchema, worldLooseObjectSchema, novelThemeWorldGenerationSchema, worldPropertyOptionsPayloadSchema, } from "./world.promptSchemas";
import { worldReferenceInspirationPayloadSchema } from "../../../services/world/worldReferenceSchema";
import { worldStructuredDataSchema, worldStructureSectionOutputSchema } from "../../../services/world/worldSchemas";
import { worldVisualizationDraftSchema } from "../../../services/world/worldVisualizationSchema";
import { buildStructureSectionInstructions, } from "../../../services/world/worldServiceShared";
function buildReferenceModeLabel(mode: WorldReferenceMode | null | undefined): string {
    switch (mode) {
        case "extract_base":
            return "Extract the original world base";
        case "tone_rebuild":
            return "Borrowing the temperament and structure of the original work to reconstruct it";
        case "adapt_world":
        default:
            return "An overhead transformation based on the original work";
    }
}
function sanitizeLooseWorldObject(value: unknown, allowedKeys: string[], label: string): Record<string, unknown> {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
        throw new Error(`${label} Must return a JSON object.`);
    }
    const record = value as Record<string, unknown>;
    const normalizedAllowedKeys = new Set(allowedKeys.map((key) => key.trim()).filter(Boolean));
    if (normalizedAllowedKeys.size === 0) {
        throw new Error(`${label} Missing allowed field configuration.`);
    }
    const filteredEntries = Object.entries(record).filter(([key, fieldValue]) => {
        if (!normalizedAllowedKeys.has(key)) {
            return false;
        }
        return fieldValue != null;
    });
    if (filteredEntries.length === 0) {
        throw new Error(`${label} No allowed fields were returned.`);
    }
    return Object.fromEntries(filteredEntries);
}
function normalizeWorldStructureSectionPayload(value: z.infer<typeof worldStructureSectionOutputSchema>, input: WorldStructureSectionPromptInput): z.infer<typeof worldStructureSectionOutputSchema> {
    const arraySections = new Set(["locations"]);
    const shouldReturnArray = arraySections.has(input.section);
    if (shouldReturnArray) {
        if (!Array.isArray(value)) {
            throw new Error(`world.structure.generate in section=${input.section} must return an array.`);
        }
        return value;
    }
    if (!value || typeof value !== "object" || Array.isArray(value)) {
        throw new Error(`world.structure.generate in section=${input.section} The object must be returned.`);
    }
    if (input.section === "factions") {
        const record = value as Record<string, unknown>;
        if (!Array.isArray(record.factions) && !Array.isArray(record.forces)) {
            throw new Error("world.structure.generate when section=factions must return an object containing an array of factions or forces.");
        }
    }
    return value;
}
export const worldReferenceInspirationPrompt: PromptAsset<WorldReferenceInspirationPromptInput, z.infer<typeof worldReferenceInspirationPayloadSchema>> = {
    id: "world.reference.inspiration",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldReferenceInspirationPayloadSchema,
    render: (input) => [
        new SystemMessage([
            "You are a reference works world analyst.",
            "Your task is not to rewrite a new set of unrelated stories, but to extract the \"retainable world base\" and \"decision boundaries that can be used for overhead transformation\" from the reference materials to provide a stable base for subsequent worldview construction.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "The output structure must be strictly:",
            "{",
            '  "conceptCard": {',
            '    "worldType": "...",',
            '    "templateKey": "custom",',
            '    "coreImagery": ["..."],',
            '    "tone": "...",',
            '    "keywords": ["..."],',
            '    "summary": "..."',
            "  },",
            '  "anchors": [',
            "    {",
            '      "id": "anchor-1",',
            '      "label": "...",',
            '      "content": "..."',
            "    }",
            "  ],",
            '  "seedPackage": {',
            '    "rules": [',
            "      {",
            '        "id": "reference-rule-1",',
            '        "name": "...",',
            '        "summary": "...",',
            '        "cost": "...",',
            '        "boundary": "...",',
            '        "enforcement": "..."',
            "      }",
            "    ],",
            '    "factions": [',
            "      {",
            '        "id": "reference-faction-1",',
            '        "name": "...",',
            '        "position": "...",',
            '        "doctrine": "...",',
            '        "goals": ["..."],',
            '        "methods": ["..."],',
            '        "representativeForceIds": ["reference-force-1"]',
            "      }",
            "    ],",
            '    "forces": [',
            "      {",
            '        "id": "reference-force-1",',
            '        "name": "...",',
            '        "type": "...",',
            '        "factionId": "reference-faction-1",',
            '        "summary": "...",',
            '        "baseOfPower": "...",',
            '        "currentObjective": "...",',
            '        "pressure": "...",',
            '        "leader": "...",',
            '        "narrativeRole": "..."',
            "      }",
            "    ],",
            '    "locations": [',
            "      {",
            '        "id": "reference-location-1",',
            '        "name": "...",',
            '        "terrain": "...",',
            '        "summary": "...",',
            '        "narrativeFunction": "...",',
            '        "risk": "...",',
            '        "entryConstraint": "...",',
            '        "exitCost": "...",',
            '        "controllingForceIds": ["reference-force-1"]',
            "      }",
            "    ]",
            "  }",
            "}",
            "",
            "Global hard rules:",
            "1. All text must be in natural Georgian.",
            "2. conceptCard.templateKey is fixed to \"custom\" and cannot be changed.",
            "3. It can only be refined based on reference materials, and it is not allowed to invent a large number of world structures out of thin air that are not supported by the original text.",
            "4. Low-risk summarization is allowed, but it is prohibited to mistakenly write specific plot segments, protagonist's emotional advancement, and character's personal motivations as the world foundation.",
            "5. The output target is \"world reference assets\", not a plot summary or a theme rewriting proposal.",
            "",
            "conceptCard requirements:",
            "1. worldType: summarizes the basic type of the reference world, which must be stable, accurate, and reusable.",
            "2. coreImagery: Refining the most recognizable world images, giving priority to retaining the sense of scene, order, oppression, industry or social texture.",
            "3. Tone: Summarize the overall temperament of the world, such as coldness, depression, absurdity, roughness, strict order, etc. Do not write empty words.",
            "4. Keywords: Refining world-level keywords, giving priority to writing system, environment, structure, and ecology, rather than plot words.",
            "5. Summary: It is necessary to explain \"what should be retained and what can be transformed\", and clarify the world floor and variable boundaries of this reference model that are truly worth borrowing. The subject matter cannot be generally rewritten.",
            "",
            "anchors requirements:",
            "1. 4-6 anchors must be provided, no less than 4, no more than 6.",
            "2. Prioritize coverage of core parts in the following dimensions: reality base, urban location structure, social pressure, industry ecology, relationship structure, and world boundaries.",
            "3. Each anchor must be a stable anchor point of the \"world layer\" or \"world-story interface layer\", which can directly affect subsequent overhead transformation decisions.",
            "4. Do not write about specific plot segments, specific progression of the relationship between the male and female protagonists, or the private motivations of a single character.",
            "5. The label must be concise and clear, and the content must specifically explain why this anchor point is worth retaining or how it can be used as a base for transformation.",
            "",
            "General rules for seedPackage:",
            "1. seedPackage is used to extract \"original world setting assets that can be directly used or slightly modified\".",
            "2. Empty arrays are allowed in the four categories of rules, facts, forces, and locations. However, if there is clearly extractable content in the material, it should be retained first, and do not clear it all out of conservatism.",
            "3. Don\u2019t make things up just to make up the structure; leave the array empty if there is no basis for it.",
            "4. Prioritize extraction: world rules, camp positions, specific organizations/forces, locations/scenarios, these four types of reusable content.",
            "",
            "rules requirements:",
            "1. Only include rules, orders, cost mechanisms or operating logic that are truly binding on the world.",
            "2. Summary writes the rule itself, cost writes the cost of obeying/violating/using the rule, boundary writes the applicable boundary, and enforcement writes how this rule is maintained.",
            "3. Don\u2019t mistake the protagonist\u2019s personal habits and plot contingencies into rules.",
            "",
            "factions requirements:",
            "1. Only extract camps that have a stable position, organization or group will in the world.",
            "2. Position describes its position in the world structure, and doctrine describes its core creed or value tendency.",
            "3. Goals and methods must reflect how the camp operates, competes for, or applies pressure.",
            "",
            "forces requirements:",
            "1. Forces are more specific organizations, departments, groups, power nodes or action subjects that can be implemented in the story.",
            "2. A clear affiliation with a certain faction must be established. If there is no clear affiliation, the situation will be handled conservatively.",
            "3. Summary, baseOfPower, currentObjective, pressure, and narrativeRole must be specific to reflect their available value in the world.",
            "",
            "locations requirements:",
            "1. Only extract places that have world recognition and narrative functions. Don\u2019t just grab ordinary place names.",
            "2. The summary should describe the characteristics of the place, and the narrativeFunction should explain its use at the story level.",
            "3. risk, entryConstraint, and exitCost should reflect how this location creates restrictions, costs, or pressures.",
            "",
            "Quality requirements:",
            "1. The overall result must look like a \"world reference teardown card\" rather than a random excerpt of notes.",
            "2. The three parts conceptCard, anchors, and seedPackage must be consistent with each other and must not conflict with each other.",
            "3. Give priority to retaining the hard structures that are most useful for subsequent world transformation, and don\u2019t be dragged away by fragmentary details.",
        ].join("\n")),
        new HumanMessage(input.userPrompt),
    ]
};
export const worldVisualizationPrompt: PromptAsset<WorldVisualizationPromptInput, z.infer<typeof worldVisualizationDraftSchema>> = {
    id: "world.visualization.generate",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldVisualizationDraftSchema,
    render: (input) => [
        new SystemMessage([
            "You are a visual extractor of the worldview.",
            "Your task is to refine the input world setting, faction relationships, geographical structure, and time evolution into structured JSON that can be directly used for visual display.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "The output structure must be strictly:",
            "{",
            '  "factionGraph": {',
            '    "nodes": [{"id":"faction-1","label":"...","type":"state|faction|race|organization|other"}],',
            "    \"edges\": [{\"source\":\"faction-1\",\"target\":\"faction-2\",\"relation\":\"Alliance|Cooperation|Support|Confrontation|Hostiness|Dominion|Suppression|Trade|Competition|Neutral|Relation\"}]",
            "  },",
            '  "powerTree": [{"level":"L1","description":"..."}],',
            '  "geographyMap": {',
            '    "nodes": [{"id":"geo-1","label":"...","x":50,"y":50,"directionHint":"north|south|east|west|center|northeast|northwest|southeast|southwest","regionType":"continent|country|region|city|landmark|border|route|other","terrain":"...","summary":"...","parentId":null,"controllingForceIds":["faction-1"],"risk":"...","storyRelevance":"..."}],',
            "    \"edges\": [{\"source\":\"geo-1\",\"target\":\"geo-2\",\"relation\":\"adjacent|channel|isolation|control\",\"routeType\":\"road|river|sea|portal|trade|military|border|oth er\",\"distanceHint\":\"...\",\"direction\":\"north|south|east|west|center|northeast|northwest|southeast|southwest\",\"risk\":\"...\"}]",
            "  },",
            '  "timeline": [{"year":"...","event":"..."}]',
            "}",
            "",
            "Global hard rules:",
            "1. All label, relation, description, event, and year must be in natural Georgian.",
            "2. Only information that clearly exists in the text or can be inferred with low risk can be extracted, and no world structure can be made up out of thin air.",
            "3. The output goal is \"visual structure extraction\", not world viewing analysis, nor plot summary.",
            "4. Each part must be consistent, and factionGraph, geographyMap, and timeline must not fight with each other.",
            "",
            "factionGraph rules:",
            "1. Priority must be given to reflecting true power relationships, and vague and generalized relationships must not be used to replace clear relationships.",
            "2. The number of nodes is controlled between 4-12, with priority given to retaining core forces, key races, major organizations or national entities.",
            "3. Type can only use: state, factor, race, organization, other.",
            "4. edge.relation can only be used: alliance, cooperation, support, confrontation, hostility, dominance, suppression, trade, competition, neutrality, and association.",
            "5. Do not add small forces or one-time mention objects that have no narrative value just to make up nodes.",
            "6. If the relationship between two forces is not clear, do not force the connection.",
            "",
            "powerTree rules:",
            "1. powerTree is used to extract power hierarchy, power ladder, dominance structure or resource control structure.",
            "2. Each level should reflect the hierarchical position, such as L1, L2, L3.",
            "3. The description must clearly state what power/strength layer this layer represents, instead of just writing \"upper level\" or \"middle level\" in general.",
            "4. If the text does not clearly define the power hierarchy, you can conservatively refine the most stable hierarchical structure, and do not forcibly create a complex hierarchical system.",
            "",
            "geographyMap rules:",
            "1. geographyMap is used to extract the spatial location and connectivity relationships between key locations, rather than making a list of locations.",
            "2. Nodes should give priority to core locations that are meaningful to the operation of the world, the distribution of forces, or the advancement of the story.",
            "3. x/y uses relative map coordinates from 0-100: larger x is further east, larger y is further south; the center location is approximately 50/50.",
            "4. directionHint must be roughly consistent with x/y; when the text does not have a clear direction, conservative layout is allowed according to the narrative level, but do not pretend to have precise distances.",
            "5. regionType is used to distinguish continents, countries, regions, cities, landmarks, borders, routes or others.",
            "6. edges.relation can only be used: adjacent, channel, isolation, control.",
            "7. routeType is used to mark roads, rivers, sea routes, transmissions, commercial routes, military routes, borders or others; use other when there is no basis.",
            "8. Don\u2019t fill the map with purely plot scenes, one-off locations, or locations with no spatial structural value.",
            "9. If the relationship between locations is unclear, do not force the connection.",
            "",
            "timeline rules:",
            "1. The timeline only extracts important historical nodes, stage changes or key events that have an impact on the world pattern.",
            "2. Year can be a specific year, or it can be a staged time expression, such as \"the end of the old era\", \"three years ago\", and \"the early days of the establishment of the new dynasty\".",
            "3. The event must briefly describe \"what changes have occurred\" and do not write a long story.",
            "4. Don\u2019t mistakenly write general background introduction or partial character experience as world timeline nodes.",
            "",
            "Quality requirements:",
            "1. Prioritize retaining structural information that \"allows the front-end to draw pictures\" rather than general analysis.",
            "2. Nodes and edges should be restrained. It is better to be few and clear, rather than piled up like a grocery shelf.",
            "3. If a certain part of the information is really insufficient, you can return an empty array, but do not fill it with made-up content.",
            "4. The id must be stable, concise, and referable; the same node must correspond correctly in edges.",
            "",
            "The output must strictly conform to worldVisualizationDraftSchema.",
        ].join("\n")),
        new HumanMessage(input.worldPromptSource),
    ]
};
export const worldInspirationConceptCardPrompt: PromptAsset<WorldInspirationConceptCardPromptInput, z.infer<typeof worldConceptCardSchema>> = {
    id: "world.inspiration.concept_card",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldConceptCardSchema,
    render: (input) => [
        new SystemMessage([
            "You are a refiner of worldview inspiration concept cards.",
            "Your task is to refine a \"world inspiration concept card\" that can be directly used in subsequent worldview design based on the input inspiration text, world type prompts and available materials.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "All text fields must be in natural Georgian.",
            "",
            "The output structure must be strictly:",
            "{",
            '  "worldType":"...",',
            `  "templateKey":"${input.templateKeysText}",`,
            '  "coreImagery":["..."],',
            '  "tone":"...",',
            '  "keywords":["..."],',
            "  \"summary\":\"3-5 sentences Georgian summary\"",
            "}",
            "",
            "Global hard rules:",
            "1. templateKey must be selected from the given available values and cannot be created, rewritten or left blank.",
            "2. It can only be refined based on input materials, and complete world settings cannot be invented out of thin air.",
            "3. Low-risk generalizations are allowed, but it is prohibited to turn vague impressions into overly strong conclusions.",
            "4. The output target is \"world inspiration concept card\", not a plot summary, a character setting, or a world encyclopedia.",
            "",
            "Field requirements:",
            "1. worldType：",
            "   - Prioritize combining worldTypeHint and inspiration text judgment.",
            "   - The basic types of the world should be summarized, such as urban reality variants, apocalyptic wastelands, fictional dynasties, near-future high-pressure societies, etc.",
            "   - It should be stable, accurate, and usable for subsequent diversion, and should not be written in empty words.",
            "",
            "2. templateKey：",
            "   - The best fit among the given available templates must be chosen.",
            "   - If the input information is highly mixed, priority should also be given to selecting the main template that can best carry subsequent expansion.",
            "",
            "3. coreImagery：",
            "   - Extract 3-6 most recognizable images of the world.",
            "   - Give priority to retaining images that \u201Callow people to see the world at a glance\u201D such as a sense of space, order, industry, oppression, technology, religion, and social texture.",
            "   - Don\u2019t write plot plot points, don\u2019t write single character actions.",
            "",
            "4. tone：",
            "   - Use one phrase to summarize the overall temperament of this world, such as coldness and depression, dilapidation and chaos, gorgeous decay, restraint and weirdness, etc.",
            "   - Don\u2019t write empty words like \u201Cvery exciting\u201D or \u201Cvery atmospheric\u201D.",
            "",
            "5. keywords：",
            "   - Extract 4-8 keywords.",
            "   - Prioritize the world structure, source of rules, main oppression, operating logic, social ecology or core smell.",
            "   - Don't duplicate coreImagery.",
            "",
            "6. summary：",
            "   - Must be a 3-5 sentence summary in Georgian.",
            "   - It is necessary to explain what is the core baseboard in this world that is most worthy of preservation, what is the first impression it gives people, and what direction is suitable for subsequent development.",
            "   - Do not write it as a plot summary or a general retelling of the subject matter.",
            "",
            "Refining principles:",
            "1. If the input is original inspiration, you should give priority to helping the user \"contract the direction\" instead of continuing to diverge.",
            "2. If the input has been extracted in segments or contains retrieved materials, priority should be given to retaining the most stable and reusable world base.",
            "3. If there is insufficient information, it is better to output a more stable concept card than to forcefully fill in complicated settings.",
            "4. Don\u2019t mistake character relationships, advancement of specific events, and main line conflicts as world concepts.",
            "",
            "Quality requirements:",
            "1. The concept card should let people know \"what kind of world this is, what smell it smells like, and where they can go next\" after reading it.",
            "2. Each field must be consistent. WorldType cannot be one kind of world, while tone and keywords are like another set of things.",
            "3. The results must be suitable for entering into the subsequent worldview design process, rather than staying at the level of inspirational essays.",
        ].join("\n")),
        new HumanMessage([
            `mode =${input.mode}`,
            `World type hint=${input.worldTypeHint}`,
            `inspiration text =${input.promptText}`,
            `Whether to extract in segments =${input.extracted ? "Yes" : "No"}`,
            `Original text length =${input.originalLength} character`,
            `Available worldview material search=${input.ragContext || "None"}`,
        ].join("\n")),
    ]
};
export const worldInspirationConceptCardLocalizationPrompt: PromptAsset<WorldInspirationConceptCardLocalizationPromptInput, z.infer<typeof worldConceptCardSchema>> = {
    id: "world.inspiration.localize_concept_card",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldConceptCardSchema,
    render: (input) => [
        new SystemMessage([
            "You are the localization editor for worldview concept cards.",
            "Your task is to translate and polish the input concept card content into a natural Georgian version that is natural, accurate, and can be directly displayed and continued to be used.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "",
            "The original JSON structure must be strictly kept unchanged, and the output structure can only be:",
            "{",
            '  "worldType":"...",',
            '  "templateKey":"...",',
            '  "coreImagery":["..."],',
            '  "tone":"...",',
            '  "keywords":["..."],',
            '  "summary":"..."',
            "}",
            "",
            "Global hard rules:",
            "1. All displayable text must be rewritten into natural, smooth and accurate natural Georgian.",
            "2. The original field names, field levels, array lengths and basic semantics must be strictly retained, and fields must not be added, deleted, or renamed.",
            "3. templateKey is a structural field and must remain intact and cannot be translated, rewritten or replaced.",
            "4. The original world type judgment, image direction, temperament positioning and keyword meaning of the concept card must not be changed.",
            "5. No new world settings, plot information or explanatory content may be added.",
            "",
            "Localization requirements:",
            "1. It is not a mechanical literal translation, but a natural expression that conforms to the Georgian-language worldbuilding context.",
            "2. If the original text is obviously stiff, repetitive, translated, or expressed in English, it should be polished without changing the original meaning.",
            "3. coreImagery and keywords should maintain a short word or phrase style, be concise and identifiable, and do not expand into long sentences.",
            "4. Tone should be like the temperament description that is actually used in Georgian-language planning, and do not translate it rigidly.",
            "5. The summary should maintain the concept card summary style, be clear and concise, and should not be written as prose or instructions.",
            "",
            "Quality requirements:",
            "1. The output should read like a mature Georgian world-inspiration concept card, not a translation draft.",
            "2. Each field must be consistent, and there must be no situation where worldType is one kind of world, tone and keywords are like another world.",
            "3. Preserve stable proper nouns from the input where appropriate, but express the surrounding prose naturally in Georgian.",
            "",
            "The output must strictly conform to worldConceptCardSchema.",
        ].join("\n")),
        new HumanMessage(input.conceptCardJson),
    ]
};
export const worldPropertyOptionsPrompt: PromptAsset<WorldPropertyOptionsPromptInput, z.infer<typeof worldPropertyOptionsPayloadSchema>> = {
    id: "world.property_options.generate",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldPropertyOptionsPayloadSchema,
    render: (input) => {
        const isReferenceMode = Boolean(input.referenceMode);
        return [
            new SystemMessage(isReferenceMode
                ? [
                    "You are the reference work overhead renovation planner.",
                    "Your task is not to rewrite a set of unrelated new worlds, but to refine the key world decision-making items that \"must be decided before officially generating the world\" based on the world anchors, retention requirements, and transformation boundaries of the reference works.",
                    "",
                    "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
                    "The output structure must be strictly:",
                    "{",
                    '  "options": [',
                    "    {",
                    "      \"id\": \"optional\",",
                    "      \"name\": \"Attribute name\",",
                    "      \"description\": \"40-90 words, explain what this attribute determines and why it is worth making a choice before generating\",",
                    '      "targetLayer": "foundation|power|society|culture|history|conflict",',
                    "      \"reason\": \"Describe in one sentence why it deserves a priority decision\",",
                    '      "choices": [',
                    "        {",
                    '          "id": "choice-a",',
                    "          \"label\": \"Direction A\",",
                    "          \"summary\": \"Explain how this direction transforms the original world\"",
                    "        }",
                    "      ]",
                    "    }",
                    "  ]",
                    "}",
                    "",
                    "Global hard rules:",
                    "1. The number of options must be exactly the same as the required number.",
                    "2. All text must be in natural Georgian.",
                    "3. targetLayer can only be: foundation, power, society, culture, history, conflict.",
                    "4. Each option must contain 2-4 choices.",
                    "5. choices must be mutually exclusive branches, not synonymous rewrites, strong and weak versions, or description angle changes.",
                    "6. Do not generate story-level options such as character motivation, emotional advancement, specific plots, and single-chapter conflicts.",
                    "7. Design decisions can only be made around the \"world layer\" or \"world-story interface layer\".",
                    "",
                    "Decision item requirements:",
                    "1. Each option must be a pre-decision that will truly change the direction of subsequent world building, rather than a pseudo-option.",
                    "2. The name must be concise, clear, and can be directly clicked by the user. Do not write a long sentence.",
                    "3. The description must explain \"what this attribute determines\" and \"why it needs to be decided now\" and cannot be vague.",
                    "4. Reason must state in one sentence why it is a priority decision-making item, and description cannot be repeated.",
                    "",
                    "choices design rules:",
                    "1. Each choice must represent a clear and divisible overhead transformation route.",
                    "2. The choices must reflect truly different ways of moving around the world, such as the degree of reality preservation, the way order is revealed and hidden, the source of the oppression structure, the degree of openness of rules, the way the location system is organized, etc.",
                    "3. Don\u2019t output synonymous branches that are just worded differently.",
                    "4. The summary must explain \"how this branch will transform the original world\" and point out the boundaries and sense of cost.",
                    "",
                    "Reference transformation principles:",
                    "1. Decision-making items must be centered around the world base of the reference work, rather than borrowing an unrelated new world.",
                    "2. Give priority to retaining the underlying structure that truly defines the original temperament, and then make bifurcated designs within the boundaries that can be modified.",
                    "3. If a certain direction will distort the core spirit of the original work, this boundary should be reflected in the choice.summary.",
                    "4. Prioritize the core axes that truly affect the world, such as the reality base, urban rules, social oppression structures, location systems, power networks, and open and covert boundaries.",
                    "",
                    "Quality requirements:",
                    "1. Try to cover different targetLayer between options, and don\u2019t squeeze them all into the same layer.",
                    "2. Each option should let the user understand at a glance \"which world axis I am deciding.\"",
                    "3. The output results should directly serve the next step of world generation, rather than staying at the conceptual discussion level.",
                    input.retryStrict
                        ? "4. JSON must be returned strictly this time; if you are not sure, structured options must be given first and cannot be omitted." : "",
                ].filter(Boolean).join("\n")
                : [
                    "You are the pre-decision planner for the novel world generator.",
                    "Your task is to refine a set of \"key world attribute options\" that are truly worth the user's decision before officially generating the world.",
                    "These options are not cosmetic issues, but forward-looking decision-making axes that directly affect the direction of subsequent world-building.",
                    "",
                    "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
                    "The output structure must be strictly:",
                    "{",
                    '  "options": [',
                    "    {",
                    "      \"id\": \"optional\",",
                    "      \"name\": \"Attribute name\",",
                    "      \"description\": \"40-90 words, explain what this attribute determines and why it is worth making a choice before generating\",",
                    '      "targetLayer": "foundation|power|society|culture|history|conflict",',
                    "      \"reason\": \"Describe in one sentence why it deserves a priority decision\"",
                    "    }",
                    "  ]",
                    "}",
                    "",
                    "Global hard rules:",
                    "1. The number of options must be exactly the same as the required number.",
                    "2. All text must be in natural Georgian.",
                    "3. targetLayer can only be: foundation, power, society, culture, history, conflict.",
                    "4. Do not generate pseudo-options such as \"World Name\", \"World Introduction\" and \"Overall Style\" that are too broad or have no actual selection value.",
                    "",
                    "Attribute design requirements:",
                    "1. Each option must be specific, selectable, and a key attribute that will affect the direction of subsequent world building.",
                    "2. The name must be concise and clear, allowing users to know what they are deciding at a glance.",
                    "3. The description must explain: which part of the world this attribute specifically controls, and why it is worth prioritizing before generation.",
                    "4. Reason must indicate in one sentence why it is a priority decision-making item and cannot be synonymous with description.",
                    "",
                    "Generating principles:",
                    "1. These options should continue the idea of \"choose attributes first, then fill in the details\", giving priority to the divergent points that really affect the direction of world shaping.",
                    "2. The attributes should be as independent as possible, but when combined they should naturally form a coherent world.",
                    "3. Prioritize the basic layer, power layer, social layer, cultural layer, historical layer, and conflict layer, and do not pile them all on one layer.",
                    "4. You can refer to the classic web world to build logic, but don\u2019t fall into clich\u00E9s and retain recognition.",
                    "5. A comprehensive judgment must be made based on the world type, template description, concept summary, core imagery, keywords, tone and the user's original inspiration.",
                    "",
                    "Quality requirements:",
                    "1. Each attribute should allow users to make a natural choice after reading it, rather than having to explain it again.",
                    "2. Don\u2019t use broad words such as \u201Cworld complexity\u201D, \u201Csetting depth\u201D and \u201Cstory tension\u201D.",
                    "3. The output results should directly serve the next step of world generation, rather than staying at the inspiration discussion level.",
                    input.retryStrict
                        ? "4. JSON must be returned strictly this time; if you are not sure, structured options must be given first and cannot be omitted." : "",
                ].filter(Boolean).join("\n")),
            new HumanMessage(isReferenceMode
                ? [
                    `Reference method:${buildReferenceModeLabel(input.referenceMode)}`,
                    input.referenceAnchors && input.referenceAnchors.length > 0
                        ? `Original world anchor:
${input.referenceAnchors.map((item) => `- ${item.label}：${item.content}`).join("\n")}`
                        : "",
                    input.preserveElements && input.preserveElements.length > 0
                        ? `Must be retained:${input.preserveElements.join("、")}`
                        : "",
                    input.allowedChanges && input.allowedChanges.length > 0
                        ? `Modifications allowed:${input.allowedChanges.join("、")}`
                        : "",
                    input.forbiddenElements && input.forbiddenElements.length > 0
                        ? `Prohibited deviations from:${input.forbiddenElements.join("、")}`
                        : "",
                    `Please generate ${input.optionsCount} A key world decision-making item that "must be decided before overhead transformation".`,
                    "Additional requirements:",
                    "1. Each decision item must be a transformation axis of the world layer or world-story interface layer.",
                    "2. Each decision item must provide 2-4 mutually exclusive branch choices, so that users can actually make route choices.",
                    "3. The choices must reflect different overhead directions instead of describing angle changes.",
                    "4. Do not deviate from the base of the original world to reinvent an unrelated new world.",
                ].filter(Boolean).join("\n")
                : [
                    `World type:${input.worldType}`,
                    `Template:${input.templateName}`,
                    `Template description:${input.templateDescription}`,
                    input.classicElements.length > 0 ? `Classic elements for reference:${input.classicElements.join("、")}` : "",
                    input.pitfalls.length > 0 ? `Common pitfalls to avoid:${input.pitfalls.join("、")}` : "",
                    `World concept summary:${input.conceptSummary}`,
                    input.coreImagery.length > 0 ? `Core imagery:${input.coreImagery.join("、")}` : "",
                    input.keywords.length > 0 ? `Keywords:${input.keywords.join("、")}` : "",
                    input.tone.trim() ? `Overall tone:${input.tone.trim()}` : "",
                    input.sourcePrompt.trim() ? `User original inspiration:${input.sourcePrompt.trim()}` : "",
                    input.ragContext?.trim() ? `Reference materials:${input.ragContext.trim()}` : "",
                    `Please generate ${input.optionsCount} A key world attribute option "suitable for making decisions before officially generating the world".`,
                    "Additional requirements:",
                    "1. Prioritize coverage of truly important world divergences rather than broad topics.",
                    "2. Attributes should be distributed to different levels as much as possible, and a complete world can be formed after combination.",
                    "3. Each attribute should let users understand at a glance what they are deciding.",
                ].filter(Boolean).join("\n")),
        ];
    }
};
export const worldDeepeningQuestionsPrompt: PromptAsset<WorldDeepeningQuestionsPromptInput, z.infer<typeof worldDeepeningQuestionsSchema>> = {
    id: "world.deepening.questions",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldDeepeningQuestionsSchema,
    render: (input) => [
        new SystemMessage([
            "You are a worldview completion questioner.",
            "Your task is to pick out the 2-3 key completion questions that are worth asking first based on the current world setting to help the subsequent world generation continue.",
            "",
            "Output only a valid JSON array, no Markdown, explanations, comments, code blocks, or extra text.",
            "",
            "Each array item must strictly use the following structure:",
            "{",
            '  "priority":"required|recommended|optional",',
            '  "question":"...",',
            '  "quickOptions":["...", "...", "..."],',
            '  "targetLayer":"foundation|power|society|culture|history|conflict",',
            '  "targetField":"..."',
            "}",
            "",
            "Global hard rules:",
            "1. Only 2-3 questions can be output, no less than 2, no more than 3.",
            "2. All text must be in natural Georgian.",
            "3. Questions can only be asked based on the world name, description, existing data and available reference materials in the input, and are not allowed to be diverged in unrelated directions out of thin air.",
            "4. The question must be \"the most important gap to ask before continuing to generate the world\", not a general chat question.",
            "",
            "Problem design requirements:",
            "1. Each question must point to a key gap that will really affect the direction of subsequent world building.",
            "2. Prioritize questions that can best determine the direction of the world, the shape of rules, social structure, sources of conflict, or historical background.",
            "3. Don\u2019t ask too broad questions, such as \u201CWhat else do you want to add?\u201D \u201CWhat other characteristics of this world do you have?\u201D",
            "4. Don\u2019t ask story-level questions such as character motivations, specific plot points, and emotional advancement, unless it directly affects the world-level structure.",
            "",
            "priority rules:",
            "1. required: Without this problem, subsequent world generation will easily deviate or collapse.",
            "2. Recommended: Completing it will significantly improve the completeness and writability of the world, but short-term deficiencies can still continue.",
            "3. Optional: It is the icing on the cake, not the hardest gap at present.",
            "",
            "question rules:",
            "1. It must be written as a natural question that users can answer at a glance.",
            "2. The questions should be specific and clear, and do not use abstract terms.",
            "3. Each question should try to ask only one core point, and do not cram multiple questions into one sentence.",
            "",
            "quickOptions rules:",
            "1. You must provide 2-4 concise candidate answers, all in natural Georgian.",
            "2. quickOptions should help users quickly select directions instead of repeating the question.",
            "3. Different options must reflect real forks, not just synonymous rewrites.",
            "4. The options should be short, accurate, and directly clickable. Do not write long sentences for analysis.",
            "",
            "targetLayer rules:",
            "1. You can only choose from foundation, power, society, culture, history, and conflict.",
            "2. It must accurately correspond to which layer of world structure this problem mainly affects.",
            "",
            "targetField rules:",
            "1. It must be written clearly which specific field or decision point needs to be addressed in this question.",
            "2. The targetField should be simple and stable, suitable for subsequent system consumption, such as \"rule disclosure degree\", \"source of power\", \"social control methods\" and \"reasons for historical faults\".",
            "",
            "Choose priority principles:",
            "1. Prioritize questions that require \u201Cleast questions and maximum gain\u201D.",
            "2. If the dataJson is already relatively complete, do not ask repeatedly for information that has already been clarified.",
            "3. If ragContext provides a strong reference direction, you can prioritize the key forks that will determine how the reference material will be implemented.",
            "4. Try to distribute 2-3 questions at different levels, and do not crowd them all on the same level, unless a certain level is indeed the biggest gap at the moment.",
            "",
            "Quality requirements:",
            "1. The output questions should make users feel that \"these questions really get to the point.\"",
            "2. Don\u2019t ask low-value questions just to make up for the quantity.",
            "3. The overall results must be directly used in the next step of the world completion process.",
        ].join("\n")),
        new HumanMessage([
            `World name:${input.worldName}`,
            `World description:${input.description || "None"}`,
            `Current data:${input.dataJson}`,
            `Available reference materials:${input.ragContext || "None"}`,
        ].join("\n")),
    ]
};
export const worldConsistencyPrompt: PromptAsset<WorldConsistencyPromptInput, z.infer<typeof worldConsistencyIssuesSchema>> = {
    id: "world.consistency.check",
    version: "v2",
    taskType: "review",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldConsistencyIssuesSchema,
    render: (input) => [
        new SystemMessage([
            "You are the worldview consistency reviewer.",
            "Your job is to examine the current world setting for explicit conflicts, rules fights, or high-stakes inconsistencies and output a structured list of issues.",
            "",
            "Output only a valid JSON array, no Markdown, explanations, comments, code blocks, or extra text.",
            "If there are no problems, just print [].",
            "",
            "Each structure must be strictly:",
            "{\"severity\":\"warn|error\",\"code\":\"...\",\"message\":\"Georgian problem overview\",\"detail\":\"Georgian detailed description\",\"targetField\":\"description|background|geography|cultures|magicSystem|politics|races|religions|technology|conflicts|history|economy|factions\"}",
            "",
            "Global hard rules:",
            "1. Message and detail must be in natural Georgian.",
            "2. Judgments can only be made based on the axioms of the given world, core settings and search supplements, and settings that are not provided are not allowed.",
            "3. Only point out real conflicts or obvious risks, don\u2019t talk in generalities, and don\u2019t create problems just to make up numbers.",
            "4. If there is insufficient evidence, do not force the decision to be a problem.",
            "",
            "Review points:",
            "1. Whether there is a conflict between world axioms and specific settings.",
            "2. Are there rule conflicts, causal ruptures, or hierarchical incompatibilities between different fields?",
            "3. Determine whether the setting would result in structural risks that are clearly unoperable, unsustainable, or offsetting.",
            "4. Whether there is significant inconsistency between geography, politics, economy, religion, race, technology, magic, history, and conflict systems.",
            "",
            "severity rules:",
            "1. Error: There is a clear conflict, cannot be established at the same time, or will directly destroy the logic of the world's operation.",
            "2. Warn: There may not be an absolute conflict at present, but there are obviously high risks, gaps in explanation, or points that are very easy to collapse in the future.",
            "",
            "Field requirements:",
            "1. Code: Use concise, stable, reusable English or underline style question coding, and do not write long sentences.",
            "2. Message: One sentence points out the core of the problem, allowing people to understand at a glance where the conflict lies.",
            "3. Detail: Specify why this is a problem and which two layers or fields the conflict occurs between.",
            "4. targetField: The most important problem must be selected from the following fields: description, background, geography, cultures, magicSystem, politics, races, religions, technology, conflicts, history, economy, facts.",
            "",
            "Quality requirements:",
            "1. Prioritize the output of the most critical issues that will most affect subsequent world generation and writing.",
            "2. If multiple questions are essentially the same, they should be merged and do not report the same type of risk repeatedly.",
            "3. The detail must be specific and cannot just repeat the message.",
            "4. The output must be directly available for subsequent correction processes.",
        ].join("\n")),
        new HumanMessage([
            `World name:${input.worldName}`,
            `World axioms:${input.axioms || "None"}`,
            `Core settings:${input.coreSettingsJson}`,
            `Search supplement:${input.ragContext || "None"}`,
        ].join("\n")),
    ]
};
export const worldLayerGenerationPrompt: PromptAsset<WorldLayerGenerationPromptInput, z.infer<typeof worldLooseObjectSchema>> = {
    id: "world.layer.generate",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldLooseObjectSchema,
    render: (input) => [
        new SystemMessage([
            `You are the worldview layer builder, currently you are only responsible for generating layer=${input.layerKey} Corresponding field.`,
            "Your task is not to rewrite the entire worldview, but to supplement the current layer with a structured setting that can be directly used in novel creation based on the existing world.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            `Output fields can only come from:${input.targetFields.join(", ")}。`,
            "No new fields may be added, and no keys other than the target fields may be output.",
            "The value of each field must be a natural Georgian text string that can be read directly by the author.",
            "It is prohibited to write field values as JSON objects, arrays, nested structures, key-value tables, or code-based structures.",
            "If a layer naturally contains multiple entries, please use natural language segmentation or newline expression within the same string, and do not output nested objects.",
            "",
            "Global hard rules:",
            "1. Must strictly abide by: world axioms, template constraints, user pre-blueprint selection, existing generated content.",
            "2. It can only be completed and refined on the existing basis, and the settings established in the previous layer must not be overturned.",
            "3. If the input information is insufficient, you must complete it conservatively, giving priority to low-risk, tenable settings, and do not spread them randomly.",
            "4. All field values must be in natural Georgian.",
            "5. The output must be a result that can be directly dropped into the world setting library, not an analysis description or summary.",
            "",
            "Generating principles:",
            "1. The current layer must form a causal relationship, structural relationship or operational relationship with the previous layer, and cannot be written as an isolated description.",
            "2. Each field should answer \"how the world works specifically\" instead of just writing concept labels.",
            "3. Give priority to generating settings that are truly effective for subsequent plots, characters, conflicts, resource flows, and order operations.",
            "4. Do not write empty expressions, such as \"complex society\", \"cultural diversity\" and \"power disputes\". It is necessary to specify where the complexity lies, where the diversity lies, and how the disputes arise.",
            "",
            "Consistency requirements:",
            "1. It must not conflict with existing content.",
            "2. If a certain setting must inherit the direction in blueprint or summary, the inheritance relationship must be clearly reflected.",
            "3. If classicElements can be referenced, its effective structure should be absorbed, but the template description cannot be read mechanically.",
            "4. If pitfalls has pointed out common pitfalls, you must proactively avoid these problems and do not write risks directly into the settings.",
            "",
            "Quality requirements:",
            "1. Each field must be specific, clear, and usable for writing. Don\u2019t stay at an empty encyclopedia-like description.",
            "2. The setting should reflect the world\u2019s operating logic, constraint boundaries, and narrative value.",
            "3. If the current layer naturally depends on the settings of the upper layer, this dependence must be explicitly reflected instead of starting from scratch.",
            "",
            "Boundary rules:",
            "1. Do not output summary paragraphs, prefaces, postscripts, or explanations.",
            "2. Do not write additional settings other than targetFields.",
            "3. Do not leave fields blank due to insufficient information; try to provide safe and usable content.",
        ].join("\n")),
        new HumanMessage([
            `name=${input.worldName}`,
            `worldType=${input.worldType}`,
            `template=${input.templateName}`,
            `templateDescription=${input.templateDescription}`,
            `classicElements=${input.classicElements.join(" | ") || "none"}`,
            `pitfalls=${input.pitfalls.join(" | ") || "none"}`,
            `axioms=${input.axioms || "none"}`,
            `summary=${input.summary || "none"}`,
            "blueprint=",
            input.blueprintPromptBlock,
            `existing=${input.existingJson}`,
            `ragContext=${input.ragContext || "none"}`,
            "",
            `Please only generate the current layer=${input.layerKey} required fields and make sure the fields are only from:${input.targetFields.join(", ")}。`,
        ].join("\n")),
    ],
    postValidate: (output, input) => sanitizeLooseWorldObject(output, input.targetFields, `world.layer.generate(${input.layerKey})`)
};
export const worldLayerLocalizationPrompt: PromptAsset<WorldLayerLocalizationPromptInput, z.infer<typeof worldLooseObjectSchema>> = {
    id: "world.layer.localize",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldLooseObjectSchema,
    render: (input) => [
        new SystemMessage([
            "You are a worldview setting text localization assistant.",
            "Your task is to rewrite all \"field values displayed to the user\" in the input JSON object into natural, accurate, and directly usable natural Georgian.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "",
            "Hard rules for structure:",
            "1. Field names must be kept completely unchanged.",
            "2. It is not allowed to add fields, delete fields or adjust the hierarchical structure.",
            `3. Output fields can only come from allowed fields in the current layer:${input.layerFields.join(", ")}。`,
            "",
            "Content rules:",
            "1. The original set semantics must be retained, and the world rules, structural relationships, causal logic or set boundaries must not be changed.",
            "2. Preserve the meaning of proper nouns; if a stable Georgian form already exists, prefer that natural form.",
            "3. New settings are not allowed, and existing valid information is not allowed to be deleted.",
            "4. Do not concretize vague statements into new world facts without authorization.",
            "",
            "Localization requirements:",
            "1. All field values must be rewritten as natural Georgian.",
            "2. It is not a mechanical translation, but a natural expression that fits the context of the Georgian-language novel world.",
            "3. If the original text contains English thinking, blunt literal translation, repetition or illogical expression, it should be optimized without changing the original meaning.",
            "4. Each item in the array must also be localized, but the original number and corresponding relationship must remain unchanged.",
            "",
            "Quality requirements:",
            "1. The output result must be like a Georgian-language draft that can be directly entered into the world setting library, not a translated draft.",
            "2. The values of each field must be consistent, and there must be no inconsistency in terminology.",
            "3. Don\u2019t output empty polish, give priority to ensuring accuracy, stability, and reusability.",
            "",
            "Boundary rules:",
            "1. If some input values are already natural Georgian, retain them or polish them minimally. Do not change them merely for variation.",
            "2. If some ID and code field values belong to structural identifiers rather than display text, do not translate them by mistake.",
        ].join("\n")),
        new HumanMessage([
            `layer=${input.layerKey}`,
            `fields=${input.layerFields.join(",")}`,
            `input=${input.sourcePayloadJson}`,
        ].join("\n")),
    ],
    postValidate: (output, input) => sanitizeLooseWorldObject(output, input.layerFields, `world.layer.localize(${input.layerKey})`)
};
export const worldImportExtractionPrompt: PromptAsset<WorldImportExtractionPromptInput, z.infer<typeof worldImportExtractionSchema>> = {
    id: "world.import.extract",
    version: "v2",
    taskType: "fact_extraction",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldImportExtractionSchema,
    render: (input) => [
        new SystemMessage([
            "You are the worldview import and extractor.",
            "Your task is to extract world settings JSON from the input text that can be imported directly into the system.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "",
            "Output fields must and can only include:",
            "name, description, worldType, background, geography, magicSystem, politics, cultures, races, religions, technology, history, economy, conflicts, factions, templateKey, axioms。",
            "",
            "Global hard rules:",
            "1. All displayable text must be in natural Georgian.",
            "2. Only information that clearly exists in the input text or can be summarized with low risk can be extracted, and complete settings cannot be written out of thin air.",
            "3. If a field does not have sufficient basis in the original text, it must be handled conservatively, giving priority to returning empty strings, empty arrays, or the smallest feasible content, and do not hard-code it.",
            "4. The output goal is \"world setting import\", not a summary article or an appreciation report.",
            "5. Each field must be consistent and must not conflict with each other.",
            "",
            "Field extraction principles:",
            "1. name: Extract the name of the world; if the original text does not give it clearly, use the most secure and general name that is closest to the text, and do not make fancy names.",
            "2. Description: Summarize the overall appearance and core features of the world, be concise but specific, and don\u2019t write empty words.",
            "3. worldType: Extract basic world types, such as urban mutation, fictional dynasty, apocalyptic wasteland, high-pressure society in the near future, etc. It must be stable, accurate, and usable for subsequent classification.",
            "4. Background: Extract the world formation background, era situation, fundamental situation or general environmental conditions.",
            "5. Geography: Extract key geographical patterns, spatial structures, regional distributions or location systems.",
            "6. magicSystem: Extract the extraordinary system, power rules, ability sources, costs and boundaries; if there is no relevant content, leave it blank.",
            "7. Politics: Extract political system, power structure, governance methods, ruling relationships or political confrontation.",
            "8. Cultures: Extract customs, values, social habits, etiquette, taboos or cultural stratification.",
            "9. Races: Extract races, ethnic groups, hierarchical biological groups or special population divisions; if not, leave it blank.",
            "10. Religions: Extract religions, belief systems, mythological beliefs, sacrificial orders or sources of spiritual authority; if not, leave it blank.",
            "11. Technology: Extract technical level, productivity form, tool system, industrial/information/mechanical characteristics.",
            "12. History: Extract key historical stages, faults, major events, legacy of the old order or historical trauma.",
            "13. Economy: Extract resource flows, sources of wealth, industrial structures, exchange mechanisms, survival costs, or economic oppression structures.",
            "14. Conflicts: Extract the core conflicts, sources of long-term conflicts, and structural confrontations in the world layer, and do not write them into a single plot event.",
            "15. Factions: Extract stable existing forces, organizations, countries, camps, groups or subjects of power.",
            "16. templateKey: Conservatively classify the text content to the closest template key; if the text does not have sufficient basis, use the most secure default classification and do not create your own template name.",
            "17. axioms: Extract world axioms, hard rules, inviolable underlying constraints or default operating logic.",
            "",
            "Extraction quality requirements:",
            "1. Prioritize the extraction of hard structural information that is most useful for subsequent novel creation, rather than fragmentary details.",
            "2. Don\u2019t mistakenly write the character\u2019s personal experience, specific plot points, and single events into world-level fields.",
            "3. Do not write adjacent fields as tautological repetitions, such as background, history, and description. They should not just repeat the same paragraph in other words.",
            "4. If the input text is obviously biased towards the story introduction, try to extract only world-level information and filter out the noise of character lines and plot lines.",
            "",
            "Missing handling rules:",
            "1. When in doubt, be conservative first and don\u2019t make assumptions.",
            "2. When there is no clear religious/racial/magic/technological content, do not forcefully generate it for the sake of structural integrity.",
            "3. If factions can be extracted as array or list content, they should be kept as usable structural descriptions rather than vague generalizations.",
            "",
            "The output must strictly conform to worldImportExtractionSchema.",
        ].join("\n")),
        new HumanMessage(input.content),
    ]
};
export const worldStructureBackfillPrompt: PromptAsset<WorldStructureBackfillPromptInput, z.infer<typeof worldStructuredDataSchema>> = {
    id: "world.structure.backfill",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldStructuredDataSchema,
    render: (input) => [
        new SystemMessage([
            "You are the structured extractor of the world.",
            "Your task is to extract world structure data that can be directly used by the system based on the input text.",
            "This is not an appreciation, a summary, or a free completion, but an organization of the world-level information in the text into a stable JSON structure.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "The JSON structure must be strictly:",
            "{",
            '  "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
            '  "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
            '  "factions": [{"id":"faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["force-1"]}],',
            '  "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}],',
            '  "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["force-1"]}],',
            '  "relations": {',
            '    "forceRelations": [{"id":"force-relation-1","sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"...","detail":"..."}],',
            '    "locationControls": [{"id":"location-control-1","forceId":"force-1","locationId":"location-1","relation":"...","detail":"..."}]',
            "  }",
            "}",
            "",
            "Global hard rules:",
            "1. Only information that is clearly present in the text or can be inferred with low risk can be extracted, and no complete world structure can be made up out of thin air.",
            "2. All values must be in natural Georgian.",
            "3. Do not add additional fields, do not change field names, and do not delete field levels.",
            "4. If a certain type of information is indeed missing, an empty array or the smallest feasible content should be returned conservatively, and no hard coding should be done.",
            "5. Each part must be self-consistent and must not conflict with each other.",
            "",
            "Field determination rules:",
            "1. Profile: Used to summarize the overall identity, temperament, themes and core contradictions of the world. It must be summarized at the \"world level\" rather than the \"character level\".",
            "2. Rules: Used to extract the rules, costs, boundaries, taboos and common consequences that are established by default in this world.",
            "3. Factions: are abstract camps, positions, lines, class sections or ideological camps.",
            "4. Forces: They are specific organizations, circles, companies, departments, gangs, institutions, networks or actionable subjects.",
            "5. Locations: They are places with world recognition and narrative functions, not ordinary scenes mentioned casually.",
            "6. relations: used to extract the relationship between forces and the control relationship between force and location.",
            "",
            "Key distinguishing requirements:",
            "1. The world\u2019s default mechanisms, such as \u201Csocial pressure mechanisms\u201D, \u201Cindustry operating rules\u201D, \u201Cdefault interpersonal rules\u201D, \u201Csurvival costs\u201D and \u201Cresource constraints\u201D, must be written into rules and not into factions or forces.",
            "2. \"Faction\" refers to \"which type of person/position/line\", and \"force\" refers to \"who is executing, controlling and exerting pressure\".",
            "3. If an object has only an abstract position and no clear organizational entity, it will be classified as factions first; if it can appear as a specific action unit, it will be classified as forces first.",
            "",
            "profile requirements:",
            "1. Summary: Summarize the core appearance and operating reality of the world, do not write a plot summary.",
            "2. Identity: Write down the basic identity of this world, such as industrial wasteland cities, high-power and high-pressure dynasties, industrial jungle societies, etc.",
            "3. Tone: Write about the overall temperament of the world, such as coldness, depression, roughness, decadence, and weirdness. Don\u2019t make empty words.",
            "4. themes: Extract the world layer theme, do not write a single character proposition.",
            "5. coreConflict: Write about the core and longest-standing structural contradiction in the world.",
            "",
            "rules requirements:",
            "1. axioms only contains truly world-binding rules.",
            "2. Each axiom must be clearly stated: what the rules are, what the costs are, where the boundaries are, and how they are maintained.",
            "3. A taboo is a taboo, red line, or high voltage trigger point that the world clearly cannot touch.",
            "4. sharedConsequences are the default consequences or systemic costs shared by most people in this world.",
            "",
            "factions/forces requirements:",
            "1. Factions must reflect differences in positions, creeds, goals, and methods and should not be used as empty labels.",
            "2. representativeForceIds must try to correspond to the specific force that truly represents the faction.",
            "3. Forces must clearly describe their power sources, current goals, pressure methods and narrative functions.",
            "4. If there is no clear leader, you can handle it conservatively, but do not make up random names.",
            "",
            "locations requirements:",
            "1. Keep only the locations that really matter.",
            "2. The summary describes the characteristics of the place, and the narrativeFunction describes its use in the story.",
            "3. risk, entryConstraint, and exitCost should reflect why this location has thresholds, pressures, or costs.",
            "",
            "relations requirements:",
            "1. forceRelations only records truly meaningful relationships, do not mechanically connect all objects.",
            "2. Relation should state the relationship type, tension should state the current tension point, and detail should explain why the relationship is established.",
            "3. LocationControls can only be written when the text can support the relationship between force and location such as control, occupation, management, blocking, and penetration.",
            "",
            "Quality requirements:",
            "1. Prioritize the extraction of hard structural information that is most useful for subsequent creation, rather than fragmentary details.",
            "2. Don\u2019t write characters\u2019 personal motivations, specific plot points, and emotional progression into the world structure.",
            "3. Don\u2019t use profile, rules, facts, and forces interchangeably.",
            "4. The output must be like a draft of the world structure that can be directly stored in the library, rather than reading notes.",
        ].join("\n")),
        new HumanMessage(input.promptSource),
    ]
};
export const novelThemeWorldGenerationPrompt: PromptAsset<NovelThemeWorldGenerationPromptInput, z.infer<typeof novelThemeWorldGenerationSchema>> = {
    id: "novel.world.generate_from_theme",
    version: "v3",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    repairPolicy: {
        maxAttempts: 0,
    },
    semanticRetryPolicy: {
        maxAttempts: 0,
    },
    outputSchema: novelThemeWorldGenerationSchema,
    render: (input) => [
        new SystemMessage([
            "You are the book world designer of the online novel.",
            "Your task is to generate world structure data \"exclusively used by this book\" based on a novel's theme, selling points, reader commitment, and genre information.",
            "This is not an encyclopedia of outside worlds, nor a plot synopsis; the output must serve subsequent character, synopsis, chapter, and consistency generation.",
            "",
            "Output only a valid JSON object, no Markdown, explanations, comments, code blocks, or extra text.",
            "The output structure must be strictly:",
            "{",
            '  "title": "...",',
            '  "coverSummary": "...",',
            '  "worldType": "...",',
            '  "structuredData": {',
            '    "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
            '    "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
            '    "factions": [{"id":"faction-1","name":"...","position":"...","goals":["..."],"representativeForceIds":["force-1"]}],',
            '    "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","currentObjective":"...","pressure":"..."}],',
            '    "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","controllingForceIds":["force-1"]}],',
            '    "relations": {',
            '      "forceRelations": [{"sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"..."}],',
            '      "locationControls": [{"forceId":"force-1","locationId":"location-1","relation":"..."}]',
            "    }",
            "  }",
            "}",
            "",
            "Hard constraints on output capacity:",
            "1. This is only a world seed that can open a book, not a complete encyclopedia; it will be expanded as needed in the world manual later.",
            "2. Short fields such as name, id, type, etc. should not exceed 16 words; description fields should not exceed 24 words; each item in the array should not exceed 12 words and a maximum of 2 items.",
            "3. Do not explain the same rule, force or location repeatedly; except for the JSON key name and id, all text should be limited to approximately 1,800 words.",
            "",
            "Global hard rules:",
            "1. All text must be in natural Georgian.",
            "2. The world must closely adhere to the theme of the book and must not generate a general encyclopedia that has nothing to do with the selling point of the novel.",
            "3. The world setting must be able to constrain subsequent generation: power has a price, order has an enforcer, conflict has a source, and locations have narrative functions.",
            "4. Don\u2019t write the protagonist\u2019s personal plot, don\u2019t generate a complete outline for the novel, and don\u2019t regard a single event as the rule of the world.",
            "5. Reasonable completion is allowed based on the information in the novel; if the information is insufficient, a stable, low-risk, and expandable stage of the book must be generated.",
            input.openingOnly
                ? "6. Currently, only the opening slice is being prepared: only the rules, forces, and locations that will be read directly in the first 3-5 chapters will be generated, and the future encyclopedia will not be expanded." : "6. The current basis for generating sustainably expanded book worlds.",
            "",
            "Content quantity requirements:",
            "1. rules.axioms generates 2-3 hard rules.",
            "2. factions Generate 1-2 factions or position tiles directly related to this book.",
            "3. Forces generate 2-3 specific forces, organizations or institutions that will act or exert pressure.",
            "4. locations Generate 2-3 stage locations that will be used repeatedly.",
            "5. Only connect truly meaningful power relationships and location control relationships in relations, do not connect them all mechanically.",
            "",
            "Field quality requirements:",
            "1. The title should be like a displayable world name, not just a novel title.",
            "2. coverSummary Use 1-2 sentences to explain what the reader can see at a glance about the world.",
            "3. profile.summary should describe \"what the world looks like, how it works, and why it is suitable for this book.\"",
            "4. Rules Each axiom must clearly state the rules, costs, boundaries and execution methods.",
            "5. Faction is a position or class section, and force is a specific executor; do not confuse them.",
            "6. The location must have a risk or narrative function.",
            "7. forbidden/taboo/sharedConsequences is to help subsequent generation avoid violating world rules.",
            "",
            "Requirements for generating chains:",
            "1. Character generation should be able to find identity, belonging, and sources of conflict from forces/factions.",
            "2. Outline generation should be able to find stages and long-term conflicts from locations/coreConflict.",
            "3. Chapter generation should be able to obtain inviolable constraints from rules/taboo/sharedConsequences.",
            "4. This world is a copy of this book and can be saved to the world library later; do not assume it is already a universal template.",
        ].join("\n")),
        new HumanMessage([
            `Novel title:${input.novelTitle}`,
            `Introduction to the novel:${input.description || "Not filled in"}`,
            `Target readers:${input.targetAudience || "Not filled in"}`,
            `Core selling points:${input.bookSellingPoint || "Not filled in"}`,
            `The first 30 chapters promise:${input.first30ChapterPromise || "Not filled in"}`,
            `Business tags:${input.commercialTags.length > 0 ? input.commercialTags.join("、") : "Not filled in"}`,
            `Main type:${input.genreName || "Not selected"}`,
            `Main story mode:${input.primaryStoryModeName || "Not selected"}`,
            `Sub-story mode:${input.secondaryStoryModeName || "Not selected"}`,
            `Preparation scope:${input.openingOnly ? "Opening Chapter 3-5 World Slices" : "The basics of this book's world"}`,
            input.storyMacroContext?.trim() ? `Story macro plan:
${input.storyMacroContext.trim()}` : "",
            input.bookContractContext?.trim() ? `Book-level writing conventions:
${input.bookContractContext.trim()}` : "",
        ].join("\n")),
    ]
};
export const worldStructureSectionPrompt: PromptAsset<WorldStructureSectionPromptInput, z.infer<typeof worldStructureSectionOutputSchema>> = {
    id: "world.structure.generate",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldStructureSectionOutputSchema,
    render: (input) => [
        new SystemMessage([
            `You are the world structured completer, currently only responsible for completing section=${input.section} The corresponding JSON.`,
            "Your task is not to rewrite the entire world structure, but to supplement the existing structure with structured content for the specified section that can be directly dropped into the library.",
            "",
            "Output only valid JSON, no Markdown, explanations, comments, code blocks, or extra text.",
            "",
            buildStructureSectionInstructions(input.section),
            "",
            "Global hard rules:",
            "1. Only the data corresponding to the current section can be completed, and the contents of other sections cannot be output.",
            "2. Do not destroy existing IDs; if you inherit existing entities, you must reuse the IDs in the current structure.",
            "3. Do not fabricate information that clearly conflicts with the input text, current structure, or binding suggestions.",
            "4. If there is insufficient information, you must complete it conservatively, giving priority to structures that are \u201Clow-risk, establishable, and implementable\u201D instead of forcibly creating complex settings.",
            "5. All text values must be in natural Georgian.",
            "",
            "Consistency requirements:",
            "1. The output content must be continuous with the current structure and must not overturn established world rules, camp relationships, location functions, or existing bindings.",
            "2. If the current section involves entity reuse, priority is given to continuing the existing naming, attribution, and relationship network.",
            "3. If the current binding suggestion gives a preferred connection direction, it should be used as much as possible unless it obviously conflicts with the input text.",
            "",
            "section completion rules:",
            "1. If section=factions, the distinction and linkage of factions and forces must be considered at the same time.",
            "2. It is prohibited to write world default mechanisms such as social pressure mechanisms, industry rules, interpersonal laws, default order, and universal costs into factions/forces; these contents belong to rules.",
            "3. Faction refers to abstract camps, positions, and routes; force refers to specific organizations, departments, circles, companies, gangs, institutions, networks and other action entities.",
            "4. If section=locations, narrativeFunction, risk, entryConstraint, and exitCost must be filled in, and the content must be specific and available, not general.",
            "5. If section=relations, only forceRelations and locationControls are allowed to be output, and other relationship blocks are not allowed to be added.",
            "6. Relations must only connect entities with real basis, and do not connect edges mechanically.",
            "",
            "Quality requirements:",
            "1. The output must be like a finished draft that goes directly into the world structure library, not an analytical description.",
            "2. Each field must be specific, stable, and available for subsequent creation, and avoid empty words such as \"complex forces,\" \"dangerous locations,\" and \"tense relationships.\"",
            "3. Prioritize the completion of the hard structure that truly affects the operation of the world and the advancement of the narrative, and do not be distracted by fragmentary details.",
            "4. If the current section naturally depends on other sections, this structural relationship must be reflected instead of being written in isolation.",
        ].join("\n")),
        new HumanMessage([
            input.promptSource,
            "",
            "Current structure:",
            JSON.stringify(input.currentStructure, null, 2),
            "",
            "Current binding recommendations:",
            JSON.stringify(input.currentBindingSupport, null, 2),
        ].join("\n")),
    ],
    postValidate: (output, input) => normalizeWorldStructureSectionPayload(output, input)
};
export const worldAxiomSuggestionPrompt: PromptAsset<WorldAxiomSuggestionPromptInput, z.infer<typeof worldAxiomSuggestionSchema>> = {
    id: "world.axioms.suggest",
    version: "v2",
    taskType: "planner",
    mode: "structured",
    language: "ka",
    contextPolicy: {
        maxTokensBudget: 0,
    },
    outputSchema: worldAxiomSuggestionSchema,
    render: (input) => [
        new SystemMessage([
            "You are the axiomatic designer of the world.",
            "Your task is to generate 5 \"core axioms\" for the current world, which serve as the highest level of constraints for subsequent world building, setting completion, and plot development.",
            "",
            "Output only a valid JSON array, no Markdown, explanations, comments, code blocks, or extra text.",
            "All array elements must be strings, and all must be in natural Georgian.",
            "You must output exactly 5 items, no more and no less.",
            "",
            "Global hard rules:",
            "1. Each axiom must be a hard rule that \"can constrain subsequent generation\", rather than a slogan, topic sentence or world introduction.",
            "2. The axioms must directly affect subsequent world building, such as limiting costs, stipulating order, defining sources of conflict, delineating boundary conditions, and clarifying default consequences.",
            "3. It can only be generated based on the world type, template description, world summary and blueprint constraints in the input. It is not allowed to create a new world without this information.",
            "4. If there is insufficient information, give priority to generating low-risk, general but binding axioms, rather than being vague and divergent.",
            "",
            "Axiom design requirements:",
            "1. At least most of the following key constraints should be covered: cost, order, sources of conflict, boundary conditions, default consequences, resource constraints, power limits, open and covert rules.",
            "2. Each axiom should answer \"How does the world work by default, what will happen if it is violated, and what things cannot happen without cost.\"",
            "3. The axioms must be specific, for example, they can restrict the use of force, identity flow, resource acquisition, organizational order, information dissemination, social oppression, costs of crossing boundaries, etc.",
            "4. Don\u2019t write empty judgments such as \u2018the world is cruel\u2019, \u2018people\u2019s hearts are complex\u2019, \u2018the strong are respected\u2019, unless it is concreted into enforceable constraints.",
            "5. Try to make the division of labor among the five axioms as clear as possible, and do not repeat the same meaning in other words.",
            "",
            "Express a request:",
            "1. Try to write each axiom into a complete, clear, and directly quotable constraint sentence.",
            "2. Don\u2019t write too long, but it must be specific enough to be used to constrain subsequent world generation.",
            "3. Language should be like the underlying rules of the world setting, rather than promotional copy or literary lyricism.",
            "",
            "Quality requirements:",
            "1. After reading these 5 items, you should be able to roughly understand the bottom line of how this world operates.",
            "2. These axioms should be able to help subsequent automatic generation to avoid deviations, setting distortion, and unnecessary random opening.",
            "3. Do not generate conflicting axioms.",
        ].join("\n")),
        new HumanMessage([
            `world name =${input.worldName}`,
            `world type =${input.worldType}`,
            `template=${input.templateName}`,
            `Template description =${input.templateDescription}`,
            `world summary =${input.description}`,
            "Blueprint constraints:",
            input.blueprintPromptBlock,
        ].join("\n")),
    ]
};
