import type { AntiAiRuleType, AntiAiSeverity, CharacterRules, LanguageRules, NarrativeRules, RhythmRules, } from "@ai-novel/shared/types/styleEngine";
export interface DefaultTemplateDefinition {
    key: string;
    name: string;
    description: string;
    category: string;
    tags: string[];
    applicableGenres: string[];
    analysisMarkdown: string;
    narrativeRules: NarrativeRules;
    characterRules: CharacterRules;
    languageRules: LanguageRules;
    rhythmRules: RhythmRules;
    defaultAntiAiRuleKeys: string[];
}
export interface DefaultAntiAiRuleDefinition {
    key: string;
    name: string;
    type: AntiAiRuleType;
    severity: AntiAiSeverity;
    description: string;
    detectPatterns: string[];
    rewriteSuggestion: string;
    promptInstruction: string;
    autoRewrite: boolean;
    enabled: boolean;
    globalBaselineEnabled: boolean;
}
export interface DefaultStarterStyleProfileDefinition {
    key: string;
    templateKey: string;
    name: string;
    description: string;
}
export const DEFAULT_STYLE_TEMPLATES: DefaultTemplateDefinition[] = [
    {
        key: "bottom-loop-reality",
        name: "Grounded Cyclical Realism",
        description: "The character's dilemma is expressed through fragmented life and repeated failures.",
        category: "Realism",
        tags: ["first person", "colloquial", "fragmented narrative"],
        applicableGenres: ["Urban", "reality", "grow"],
        analysisMarkdown: "The narrative tension is formed by time advancement and reality gap, and the core dilemma is not resolved at the end.",
        narrativeRules: {
            progressionMode: "time_sequence",
            sceneUnitPattern: ["behavior", "gap", "self-rationalization"],
            multiPov: false,
            looping: true,
            endingStyle: "unresolved",
            summary: "Advance life in fragments and do not conduct a comprehensive review.",
        },
        characterRules: {
            allowSelfReflection: false,
            emotionExpression: "behavior_only",
            defenseMechanisms: ["Hard-spoken", "transfer", "self-rationalization"],
            facePriority: true,
            dialogueStyle: "short_colloquial",
            summary: "Character emotions are expressed through actions and words.",
        },
        languageRules: {
            register: "colloquial",
            roughness: 0.8,
            allowIncompleteSentences: true,
            allowSwearing: true,
            sentenceVariation: "high",
            allowUselessDetails: true,
            summary: "The language is rough and colloquial, allowing for the noise of life.",
        },
        rhythmRules: {
            pace: "medium_fast",
            paragraphDensity: "high",
            allowFragmentedFlow: true,
            actionOverExplanation: true,
            summary: "The paragraphs are dense, and the action precedes the explanation.",
        },
        defaultAntiAiRuleKeys: [
            "forbid-explicit-psychology",
            "forbid-ending-elevation",
            "encourage-useless-action",
            "encourage-reality-gap",
            "encourage-hard-mouth-compensation",
        ],
    },
    {
        key: "power-up-escalation",
        name: "Progressive Adventure",
        description: "Escalate goals, obstacles, choices, and earned rewards while maintaining clear causality.",
        category: "Progression",
        tags: ["sense of propulsion", "profit point", "Conflict escalates"],
        applicableGenres: ["Urban", "Fantasy", "passionate"],
        analysisMarkdown: "Every scene must advance a goal, obstacle, choice, consequence, or earned payoff while preserving clear causality and rising pressure.",
        narrativeRules: {
            progressionMode: "goal_driven",
            sceneUnitPattern: ["target", "hinder", "suppress", "reversal gains"],
            multiPov: false,
            looping: false,
            endingStyle: "hook",
            summary: "Promote around the goal and realize partial benefits as soon as possible.",
        },
        characterRules: {
            allowSelfReflection: true,
            emotionExpression: "dialogue_and_action",
            defenseMechanisms: [],
            facePriority: false,
            dialogueStyle: "direct",
            summary: "The characters express themselves directly, and their emotions switch with the victory or defeat.",
        },
        languageRules: {
            register: "direct",
            roughness: 0.55,
            allowIncompleteSentences: false,
            allowSwearing: false,
            sentenceVariation: "medium",
            allowUselessDetails: false,
            summary: "The sentence structure is clear to reduce invalid distracting information.",
        },
        rhythmRules: {
            pace: "fast",
            paragraphDensity: "medium",
            allowFragmentedFlow: false,
            actionOverExplanation: true,
            summary: "Prioritize conflicts and consequences, stay less.",
        },
        defaultAntiAiRuleKeys: [
            "forbid-theme-summary",
            "risk-dialogue-too-functional",
            "risk-three-paragraphs-exposition",
        ],
    },
    {
        key: "suspense-pressure",
        name: "Escalating Suspense",
        description: "Create a sense of uneasiness through information obscuration, detail anomalies and pressure superposition.",
        category: "Suspense flow",
        tags: ["sense of oppression", "information gap", "unusual details"],
        applicableGenres: ["Suspense", "Thriller", "reality"],
        analysisMarkdown: "Extraordinary details, information gaps and rhythm are used to promote suspense layer by layer.",
        narrativeRules: {
            progressionMode: "mystery_escalation",
            sceneUnitPattern: ["Site details", "Abnormal", "Misjudgment", "new risks"],
            multiPov: false,
            looping: false,
            endingStyle: "suspense",
            summary: "Prioritize creating information gaps and an atmosphere of oppression.",
        },
        characterRules: {
            allowSelfReflection: true,
            emotionExpression: "reaction_only",
            defenseMechanisms: ["depress"],
            facePriority: false,
            dialogueStyle: "restrained",
            summary: "The character reacts with restraint and fear shows through the reaction.",
        },
        languageRules: {
            register: "restrained",
            roughness: 0.45,
            allowIncompleteSentences: true,
            allowSwearing: false,
            sentenceVariation: "medium_high",
            allowUselessDetails: true,
            summary: "The details are precise and a small amount of noise is retained to enhance the sense of presence.",
        },
        rhythmRules: {
            pace: "medium",
            paragraphDensity: "medium_high",
            allowFragmentedFlow: true,
            actionOverExplanation: true,
            summary: "Create tension through rhythmic closing and information delay.",
        },
        defaultAntiAiRuleKeys: [
            "forbid-explicit-psychology",
            "forbid-theme-summary",
            "risk-even-paragraph-length",
            "encourage-reality-gap",
        ],
    },
    {
        key: "emotional-tension",
        name: "Relationship Tension",
        description: "Creating relational tension through misplaced expressions, pauses, and misreadings.",
        category: "Relationship Drama",
        tags: ["misread", "pull", "sense of pause"],
        applicableGenres: ["Romance", "Urban", "group portrait"],
        analysisMarkdown: "Characters do not express core emotions directly and rely on misreadings, pauses, and reactions to drive relationship changes.",
        narrativeRules: {
            progressionMode: "relationship_push_pull",
            sceneUnitPattern: ["action", "implication", "misread", "Avoid"],
            multiPov: false,
            looping: false,
            endingStyle: "emotional_hook",
            summary: "Advance through relationship dislocation rather than direct explanation.",
        },
        characterRules: {
            allowSelfReflection: true,
            emotionExpression: "subtext",
            defenseMechanisms: ["Avoid", "test", "Hard-spoken"],
            facePriority: true,
            dialogueStyle: "subtext_heavy",
            summary: "Emotions are expressed through pauses, movements, and implication.",
        },
        languageRules: {
            register: "natural",
            roughness: 0.35,
            allowIncompleteSentences: true,
            allowSwearing: false,
            sentenceVariation: "high",
            allowUselessDetails: true,
            summary: "The language is natural and allows for blank spaces and pauses.",
        },
        rhythmRules: {
            pace: "medium_slow",
            paragraphDensity: "medium",
            allowFragmentedFlow: true,
            actionOverExplanation: false,
            summary: "Leave room for relationship responses, but avoid empty lyricism.",
        },
        defaultAntiAiRuleKeys: [
            "forbid-direct-preaching",
            "forbid-ending-elevation",
            "risk-dialogue-too-functional",
            "encourage-useless-action",
        ],
    },
    {
        key: "ensemble-weave",
        name: "Ensemble Weave",
        description: "The events are intertwined with multiple action lines and perspectives.",
        category: "group portrait flow",
        tags: ["Multiple roles", "intertwined", "information flow"],
        applicableGenres: ["group portrait", "Urban", "Suspense"],
        analysisMarkdown: "Multiple roles are advanced in parallel, but the expression and cognitive scope of each role must be clearly distinguished.",
        narrativeRules: {
            progressionMode: "multi_thread",
            sceneUnitPattern: ["character action", "local information", "cross influence"],
            multiPov: true,
            looping: false,
            endingStyle: "cross_hook",
            povSwitchStyle: "controlled",
            summary: "Work on multiple lines simultaneously, but the switching of perspectives must be controlled.",
        },
        characterRules: {
            allowSelfReflection: true,
            emotionExpression: "mixed",
            defenseMechanisms: [],
            facePriority: false,
            dialogueStyle: "distinct_by_role",
            summary: "The voices of different characters must be different.",
        },
        languageRules: {
            register: "flexible",
            roughness: 0.45,
            allowIncompleteSentences: true,
            allowSwearing: false,
            sentenceVariation: "high",
            allowUselessDetails: false,
            summary: "Keep roles distinct and avoid everyone speaking the same.",
        },
        rhythmRules: {
            pace: "balanced",
            paragraphDensity: "medium",
            allowFragmentedFlow: false,
            actionOverExplanation: true,
            summary: "Multiple lines are intertwined but the rhythm is not chaotic.",
        },
        defaultAntiAiRuleKeys: [
            "risk-dialogue-too-functional",
            "risk-repeated-sentence-structure",
            "forbid-theme-summary",
        ],
    },
    {
        key: "immersive-daily",
        name: "Immersive Everyday Life",
        description: "Build continuous immersion through life details and subtle emotional changes.",
        category: "Slice of Life",
        tags: ["sense of life", "immerse", "Small details"],
        applicableGenres: ["daily", "cure", "Urban"],
        analysisMarkdown: "It is allowed to retain life-like actions and invalid information, but the core emotions must still flow naturally through the scene.",
        narrativeRules: {
            progressionMode: "scene_immersion",
            sceneUnitPattern: ["action", "environment", "relationship response"],
            multiPov: false,
            looping: false,
            endingStyle: "soft_open",
            summary: "Focus on scene experience and relationship temperature.",
        },
        characterRules: {
            allowSelfReflection: true,
            emotionExpression: "light_behavior",
            defenseMechanisms: [],
            facePriority: false,
            dialogueStyle: "daily_natural",
            summary: "The characters express themselves naturally without using high-intensity dramatic sentences.",
        },
        languageRules: {
            register: "colloquial",
            roughness: 0.25,
            allowIncompleteSentences: true,
            allowSwearing: false,
            sentenceVariation: "medium_high",
            allowUselessDetails: true,
            summary: "Keep the details and noises of life without pursuing neatness.",
        },
        rhythmRules: {
            pace: "slow",
            paragraphDensity: "medium",
            allowFragmentedFlow: true,
            actionOverExplanation: false,
            summary: "Slow down for immersion, but avoid idling.",
        },
        defaultAntiAiRuleKeys: [
            "forbid-ending-elevation",
            "risk-even-paragraph-length",
            "encourage-useless-action",
        ],
    },
    {
        key: "cold-professional",
        name: "Restrained Professional",
        description: "Suppress emotions with professional facts and industry details to create a sense of restrained pressure.",
        category: "Professional stream",
        tags: ["Professional details", "restrain", "Facts overwhelm emotions"],
        applicableGenres: ["workplace", "reality", "Suspense"],
        analysisMarkdown: "Industry facts and procedural details are given priority, emotions are not stated directly, and information density is higher than lyrical density.",
        narrativeRules: {
            progressionMode: "fact_driven",
            sceneUnitPattern: ["facts", "action", "professional judgment", "Consequences"],
            multiPov: false,
            looping: false,
            endingStyle: "pressure_continue",
            summary: "Let professional facts carry the narrative weight.",
        },
        characterRules: {
            allowSelfReflection: false,
            emotionExpression: "suppressed",
            defenseMechanisms: ["restrain"],
            facePriority: false,
            dialogueStyle: "informational",
            summary: "Emotions are embedded in professional actions and factual choices.",
        },
        languageRules: {
            register: "professional",
            roughness: 0.2,
            allowIncompleteSentences: false,
            allowSwearing: false,
            sentenceVariation: "medium",
            allowUselessDetails: false,
            summary: "Prioritize terminology and facts, avoid cheap phrases.",
        },
        rhythmRules: {
            pace: "balanced",
            paragraphDensity: "medium_high",
            allowFragmentedFlow: false,
            actionOverExplanation: true,
            summary: "The information density is high, but the explanation is not lavish.",
        },
        defaultAntiAiRuleKeys: [
            "forbid-direct-preaching",
            "forbid-theme-summary",
            "risk-repeated-sentence-structure",
        ],
    },
    {
        key: "absurd-dark-humor",
        name: "Absurd Dark Humor",
        description: "Create dark humor through contrast, cold observation and absurd details.",
        category: "black humor",
        tags: ["Absurd", "Contrast", "cold feeling"],
        applicableGenres: ["Urban", "black humor", "reality"],
        analysisMarkdown: "Contrasts and absurd details are used to amplify real-life dilemmas, and laughter and oppression exist at the same time.",
        narrativeRules: {
            progressionMode: "contrast_driven",
            sceneUnitPattern: ["realistic details", "Absurd deviation", "cold reaction"],
            multiPov: false,
            looping: false,
            endingStyle: "bitter_aftertaste",
            summary: "Rely on contrast and cold observation rather than lively complaints.",
        },
        characterRules: {
            allowSelfReflection: false,
            emotionExpression: "deadpan",
            defenseMechanisms: ["self-deprecating", "transfer"],
            facePriority: true,
            dialogueStyle: "deadpan_colloquial",
            summary: "Emotions are hidden in cold reactions and harsh words.",
        },
        languageRules: {
            register: "colloquial",
            roughness: 0.5,
            allowIncompleteSentences: true,
            allowSwearing: true,
            sentenceVariation: "high",
            allowUselessDetails: true,
            summary: "Absurd impurities and cold humor are allowed.",
        },
        rhythmRules: {
            pace: "balanced",
            paragraphDensity: "medium_high",
            allowFragmentedFlow: true,
            actionOverExplanation: true,
            summary: "The contrast almost lands quickly, so don\u2019t explain the punchline.",
        },
        defaultAntiAiRuleKeys: [
            "forbid-explicit-psychology",
            "forbid-ending-elevation",
            "encourage-reality-gap",
            "encourage-hard-mouth-compensation",
        ],
    },
];
export const DEFAULT_STARTER_STYLE_PROFILES: DefaultStarterStyleProfileDefinition[] = [
    {
        key: "starter-power-up",
        templateKey: "power-up-escalation",
        name: "My Progressive Adventure Style",
        description: "A practical starting profile for clear goals, earned payoffs, escalating obstacles, and chapter-level progress.",
    },
    {
        key: "starter-suspense",
        templateKey: "suspense-pressure",
        name: "My Escalating Suspense Style",
        description: "It is suitable for stories about anomalies, rules, investigations and approaching dangers. It will help you stabilize the sense of oppression and information gap first.",
    },
    {
        key: "starter-emotional",
        templateKey: "emotional-tension",
        name: "My Relationship Tension Style",
        description: "Suitable for stories of relationship promotion, misunderstanding and emotional fulfillment, there must first be a set of relationship-based expression bases that can be written directly.",
    },
    {
        key: "starter-daily",
        templateKey: "immersive-daily",
        name: "My Everyday Immersion Style",
        description: "It is suitable for healing, companionship, life management and gentle growth stories, with priority given to ensuring a sense of life and immersion.",
    },
];
export const LEGACY_DEFAULT_ANTI_AI_RULES: DefaultAntiAiRuleDefinition[] = [
    {
        key: "forbid-explicit-psychology",
        name: "Explanatory psychological descriptions are prohibited",
        type: "forbidden",
        severity: "high",
        description: "It is forbidden to directly use sentences such as \"he felt\" and \"he realized\" to explain the character's psychology.",
        detectPatterns: ["he feels", "she feels", "he realized", "she realized", "he understands", "she understands"],
        rewriteSuggestion: "Change psychological interpretations into actions, tone, pauses, environmental responses, or consequences.",
        promptInstruction: "It is forbidden to directly explain the character's psychology. The character's state must be reflected through behavior, action, tone or environmental reaction.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "forbid-ending-elevation",
        name: "Sublimation at the end of paragraph is prohibited",
        type: "forbidden",
        severity: "high",
        description: "It is forbidden to use summary sentences at the end of a paragraph or at the end to sublimate the theme.",
        detectPatterns: ["life is", "Destiny will always be", "in the final analysis", "After all", "this is"],
        rewriteSuggestion: "Delete sublimated sentences and return to specific actions, scenes, or unresolved situations.",
        promptInstruction: "It is forbidden to sublimate or summarize the theme at the end of the paragraph. The ending must fall back to the specific situation.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "forbid-theme-summary",
        name: "Summarizing topics is prohibited",
        type: "forbidden",
        severity: "high",
        description: "It is forbidden to write paragraphs that summarize the central idea or refine the principles of life.",
        detectPatterns: ["This shows", "this means", "in the final analysis", "Actually it is"],
        rewriteSuggestion: "Delete topic summaries and let the information emerge naturally through events and consequences.",
        promptInstruction: "Don\u2019t summarize the topic or distill the central idea for the reader.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "forbid-direct-preaching",
        name: "Direct preaching is prohibited",
        type: "forbidden",
        severity: "medium",
        description: "Authors are prohibited from making direct value judgments and preaching for characters or readers.",
        detectPatterns: ["we all should", "People must learn", "what really matters is"],
        rewriteSuggestion: "Change it to the character's specific situation or dialogue instead of abstract preaching.",
        promptInstruction: "Direct preaching or value judgment is prohibited, and the meaning falls on the event itself.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-even-paragraph-length",
        name: "Paragraph length is too neat",
        type: "risk",
        severity: "medium",
        description: "The length and rhythm of the paragraphs are too average, which easily creates the feeling of AI composition.",
        detectPatterns: ["Neat paragraphs", "average tempo"],
        rewriteSuggestion: "Break the balance of paragraph lengths and allow sentences and paragraphs to have natural ups and downs.",
        promptInstruction: "Be careful not to make each paragraph too neat, average, and like a standard essay.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-three-paragraphs-exposition",
        name: "Three consecutive explanatory narratives",
        type: "risk",
        severity: "high",
        description: "Several consecutive paragraphs with only explanation and no action will weaken the sense of scene.",
        detectPatterns: ["continuous explanation", "no action"],
        rewriteSuggestion: "Insert actions, dialogues, and environmental feedback, and reduce chain descriptions.",
        promptInstruction: "Be careful to avoid consecutive paragraphs with only explanation and no action or dialogue.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-dialogue-too-functional",
        name: "Dialogue purely functional advancement",
        type: "risk",
        severity: "medium",
        description: "The dialogue only advances information, without the tone of characters and the noise of life.",
        detectPatterns: ["tell you", "we want now", "Next"],
        rewriteSuggestion: "Fill in pauses, detours, differences in tone, and invalid information.",
        promptInstruction: "Dialogue should not only serve the function of advancing the plot, but should retain the tone of the characters and the noise of life.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-repeated-sentence-structure",
        name: "Sentence repetition rate is too high",
        type: "risk",
        severity: "medium",
        description: "Continuous sentences are too neat and can easily appear mechanical.",
        detectPatterns: ["first", "then", "Then", "finally"],
        rewriteSuggestion: "Spread out the sentence length and the way you start sentences, and break up the structure.",
        promptInstruction: "Be wary of repeated sentence patterns and parallel expressions.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "encourage-useless-action",
        name: "Encourage meaningless actions",
        type: "encourage",
        severity: "low",
        description: "Encourage the addition of small actions that are real but do not push the main line to enhance the human touch.",
        detectPatterns: [],
        rewriteSuggestion: "Add in small movements such as scratching the head, lighting a cigarette, picking up packages, and moving chairs.",
        promptInstruction: "Prioritize adding small actions that are real but do not promote the main line to increase the sense of life.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
    {
        key: "encourage-reality-gap",
        name: "Encourage reality gap",
        type: "encourage",
        severity: "low",
        description: "Let there be a gap between the character's expectations and the actual results.",
        detectPatterns: [],
        rewriteSuggestion: "Fill the gap between character expectations and actual results.",
        promptInstruction: "Prioritize creating a gap in reality so that character expectations and results are not completely consistent.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
    {
        key: "encourage-hard-mouth-compensation",
        name: "Encourage harsh words to compensate",
        type: "encourage",
        severity: "low",
        description: "After the character is frustrated, he uses harsh words, deflects or seeks compensation to maintain his dignity.",
        detectPatterns: [],
        rewriteSuggestion: "Give a character a compliment or self-justification.",
        promptInstruction: "When a character is frustrated, he or she can make up for it by speaking harshly, diverting, or looking for compensation.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
    {
        key: "encourage-life-noise",
        name: "Encourage living noise",
        type: "encourage",
        severity: "low",
        description: "Appropriately add life noises that are not completely related to the main line to increase the sense of presence.",
        detectPatterns: [],
        rewriteSuggestion: "Add in ambient sounds, noises, small interruptions or life information.",
        promptInstruction: "Appropriately retain life noise and invalid information to enhance the sense of presence.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
];

export const DEFAULT_ANTI_AI_RULES: DefaultAntiAiRuleDefinition[] = [
    {
        key: "forbid-explicit-psychology",
        name: "Replace explanatory psychology with evidence",
        type: "forbidden",
        severity: "high",
        description: "Flags Georgian prose that explains an emotion or realization instead of making it legible through action, voice, perception, or consequence.",
        detectPatterns: ["იგრძნო, რომ", "მიხვდა, რომ", "გააცნობიერა, რომ"],
        rewriteSuggestion: "Express the state through a specific action, pause, bodily response, spoken choice, or changed perception.",
        promptInstruction: "Do not explain a character's psychology in summary form. In natural Georgian, reveal it through behavior, sensory attention, rhythm, dialogue, or consequence.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "forbid-ending-elevation",
        name: "Avoid artificial concluding elevation",
        type: "forbidden",
        severity: "high",
        description: "Flags paragraph or scene endings that switch into a generic life lesson or inflated thematic conclusion.",
        detectPatterns: ["ასეთია ცხოვრება", "ბოლოს და ბოლოს", "სწორედ ეს არის"],
        rewriteSuggestion: "End on a concrete image, action, consequence, unanswered pressure, or relationship beat.",
        promptInstruction: "Do not end Georgian paragraphs or scenes with generic wisdom or an artificial thematic summary; return to the concrete situation.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "forbid-theme-summary",
        name: "Do not summarize the theme for the reader",
        type: "forbidden",
        severity: "high",
        description: "Flags abstract interpretation that tells the reader what events mean instead of allowing meaning to emerge from the scene.",
        detectPatterns: ["ეს გვიჩვენებს, რომ", "ეს ნიშნავს, რომ", "მთავარი ის არის, რომ"],
        rewriteSuggestion: "Remove the thesis sentence and let the event, image, dialogue, or consequence carry the meaning.",
        promptInstruction: "Never state the moral or central idea on the reader's behalf. Let meaning emerge through Georgian narrative action and consequence.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "forbid-direct-preaching",
        name: "Avoid direct preaching",
        type: "forbidden",
        severity: "medium",
        description: "Flags authorial value judgments and bureaucratic moral instruction that override character experience.",
        detectPatterns: ["ყველამ უნდა", "ადამიანმა უნდა ისწავლოს", "ნამდვილად მნიშვნელოვანია"],
        rewriteSuggestion: "Turn the claim into a character's situated choice, disagreement, action, or dialogue.",
        promptInstruction: "Avoid direct preaching, bureaucratic Georgian, and universal moral claims. Keep judgment grounded in characters and events.",
        autoRewrite: true,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-even-paragraph-length",
        name: "Paragraph rhythm is too uniform",
        type: "risk",
        severity: "medium",
        description: "Detects mechanically even sentence and paragraph lengths that flatten Georgian prose rhythm.",
        detectPatterns: [],
        rewriteSuggestion: "Vary sentence openings, lengths, pauses, and paragraph boundaries according to scene pressure.",
        promptInstruction: "Use varied Georgian sentence and paragraph rhythm; do not make every unit equally polished, balanced, or complete.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-three-paragraphs-exposition",
        name: "Exposition replaces the scene",
        type: "risk",
        severity: "high",
        description: "Detects sustained explanation without action, dialogue, sensory change, decision, or consequence.",
        detectPatterns: [],
        rewriteSuggestion: "Move essential information into action, dialogue, objects, setting response, or a character's immediate decision.",
        promptInstruction: "Do not stack explanatory paragraphs. Keep Georgian exposition attached to a live scene, concrete need, and changing situation.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-dialogue-too-functional",
        name: "Characters speak with one functional voice",
        type: "risk",
        severity: "medium",
        description: "Detects dialogue that only transfers plot information and gives every speaker the same polished voice.",
        detectPatterns: [],
        rewriteSuggestion: "Differentiate vocabulary, syntax, hesitation, implication, politeness, and what each speaker refuses to say.",
        promptInstruction: "Give every character a distinct, natural Georgian voice. Dialogue must carry intention and relationship, not only information.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "risk-repeated-sentence-structure",
        name: "Repeated connectors and sentence frames",
        type: "risk",
        severity: "medium",
        description: "Detects repeated connectors, identical openings, excessive pronouns, and mechanically parallel Georgian sentences.",
        detectPatterns: ["შემდეგ", "ამის შემდეგ", "საბოლოოდ"],
        rewriteSuggestion: "Remove unnecessary connectors and pronouns; vary clause order, focus, length, and sentence entry.",
        promptInstruction: "Avoid repeated connectors, excessive pronouns, and cloned sentence structures. Preserve natural Georgian information order and agreement.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: true,
    },
    {
        key: "encourage-useless-action",
        name: "Allow incidental human action",
        type: "encourage",
        severity: "low",
        description: "Encourages small, credible actions that reveal presence and character without advancing the main plot mechanically.",
        detectPatterns: [],
        rewriteSuggestion: "Add one context-appropriate gesture, interruption, adjustment, or interaction with an object.",
        promptInstruction: "When useful, include incidental physical behavior that makes Georgian scenes feel inhabited rather than engineered.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
    {
        key: "encourage-reality-gap",
        name: "Use expectation-reality gaps",
        type: "encourage",
        severity: "low",
        description: "Encourages a believable difference between what a character expects and what actually happens.",
        detectPatterns: [],
        rewriteSuggestion: "Make the result depart from the expectation in a way caused by the scene and character choices.",
        promptInstruction: "Use credible expectation-reality gaps to create texture, pressure, humor, or consequence.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
    {
        key: "encourage-hard-mouth-compensation",
        name: "Let characters protect their dignity",
        type: "encourage",
        severity: "low",
        description: "Encourages culturally and personally credible face-saving after embarrassment or defeat.",
        detectPatterns: [],
        rewriteSuggestion: "Show the character deflecting, minimizing, joking, changing the subject, or reframing the loss in their own voice.",
        promptInstruction: "After embarrassment, let a character protect dignity through natural Georgian dialogue or behavior rather than authorial explanation.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
    {
        key: "encourage-life-noise",
        name: "Preserve useful everyday texture",
        type: "encourage",
        severity: "low",
        description: "Encourages selective everyday sound, interruption, and background detail that grounds the scene.",
        detectPatterns: [],
        rewriteSuggestion: "Add one relevant sound, interruption, practical detail, or minor social friction without derailing the scene.",
        promptInstruction: "Keep selective everyday texture in Georgian scenes, but do not turn it into filler or a decorative inventory.",
        autoRewrite: false,
        enabled: true,
        globalBaselineEnabled: false,
    },
];
