const CONTEXT_GROUP_LABELS: Record<string, string> = {
  writing_platform: "Writing profile",
  creation_intent: "Creative intent",
  short_story_plan: "Short-story plan",
  short_story_continuity: "Short-story continuity",
  book_style: "Book style",
  book_contract: "Book contract",
  chapter_boundary: "Chapter boundary",
  chapter_mission: "Chapter mission",
  character_dynamics: "Character dynamics",
  character_hard_facts: "Character hard facts",
  character_resource_context: "Character resources",
  continuation_constraints: "Continuation constraints",
  custom_slot: "Custom constraints",
  historical_issues: "Historical review issues",
  incremental_round_context: "Incremental generation round",
  local_state: "Current situation",
  narrative_progress_hint: "Narrative progress hint",
  obligation_contract: "Chapter obligation contract",
  open_conflicts: "Open conflicts",
  opening_constraints: "Opening constraints",
  participant_subset: "Active character subset",
  payoff_directives: "Setup and payoff directives",
  payoff_ledger: "Setup and payoff ledger",
  previous_chapter_hook: "Previous chapter hook",
  previous_chapter_tail: "Previous chapter ending",
  rag_context: "Retrieved context",
  reader_experience: "Reader experience contract",
  recent_chapters: "Recent chapter summaries",
  repair_boundaries: "Revision boundaries",
  repair_issues: "Revision issues",
  state_goal: "State and goal",
  story_macro: "Macro story structure",
  structure_obligations: "Structural obligations",
  style_contract: "Style contract",
  timeline_context: "Timeline",
  volume_window: "Volume window",
  world_rules: "World rules",
  world_slice: "World slice",
};

export function formatContextGroupLabel(group: string): string {
  return CONTEXT_GROUP_LABELS[group] ?? group;
}
